<!-- Modal -->
<div class="modal fade mobile-nav" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <?php include ($block->getTemplateFile('Magento_Search::form.mini.phtml')) ?>
      </div>
      <div class="modal-body">
				<ul class="nav nav-tabs nav-justified">
				  <li><a href="#">SHOP</a></li>
				</ul>
				<ul class="nav nav-pills nav-justified">
				  <li><a href="#">shop the shot</a></li>
					<li><a href="#">editors&#x27; picks</a></li>
					<li><a href="#">made in canada</a></li>
					<li><a href="#">from the current issue</a></li>
				</ul>
      </div>
    </div>
  </div>
</div>