<ul class="social">
	<li><a href="https://houseandhome.com/twitter" target="_blank"><i class="icon ion-social-twitter"></i></a></li>
	<li><a href="https://houseandhome.com/facebook" target="_blank"><i class="icon ion-social-facebook"></i></a></li>
	<li><a href="https://houseandhome.com/instagram" target="_blank"><i class="icon ion-social-instagram"></i></a></li>
	<li><a href="https://houseandhome.com/pinterest" target="_blank"><i class="icon ion-social-pinterest"></i></a></li>
</ul>