<ul class="social">
	<li><a href="https://houseandhome.com/twitter"><i class="icon ion-social-twitter"></i></a></li>
	<li><a href="https://houseandhome.com/facebook"><i class="icon ion-social-facebook"></i></a></li>
	<li><a href="https://houseandhome.com/instagram"><i class="icon ion-social-instagram"></i></a></li>
	<li><a href="https://houseandhome.com/pinterest"><i class="icon ion-social-pinterest"></i></a></li>
</ul>