<?php
/**
 * Mageplaza_SocialLogin extension
 *                     NOTICE OF LICENSE
 *
 *                     This source file is subject to the MIT License
 *                     that is bundled with this package in the file LICENSE.txt.
 *                     It is also available through the world-wide-web at this URL:
 *                     http://opensource.org/licenses/mit-license.php
 *
 * @category  Mageplaza
 * @package   Mageplaza_SocialLogin
 * @copyright Copyright (c) 2016
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>

<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs">
      <li><a href="#login" data-toggle="tab">Login</a></li>
      <li><a href="#signup" data-toggle="tab">Sign Up</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="login">
        <div class="social-login block-container authentication">
          <div class="block social-login-customer-authentication">
            <div class="block-content" aria-labelledby="block-customer-login-heading">
              <form class="form-customer-login" id="social-form-login" data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset login" data-hasrequired="<?php echo __('* Required Fields') ?>">
                  <div class="field email required">
                    <input name="username" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"
                    <?php endif; ?> id="email" type="email" class="input-text" title="
                    <?php /* @escapeNotVerified */ echo __( 'Email') ?>" data-validate="{required:true, 'validate-email':true}" placeholder="Email *">
                  </div>
                  <div class="field password required">
                    <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"
                    <?php endif; ?> class="input-text" id="pass" title="
                    <?php /* @escapeNotVerified */ echo __( 'Password') ?>" data-validate="{required:true, 'validate-password':true}" placeholder="Password *">
                  </div>
                  <?php echo $block->getChildHtml('form_additional_info'); ?>
                  <?php echo $block->getChildHtml('login.captcha') ?>
                  <div class="actions-toolbar login">
                    <div class="forgot-pass"><a class="action remind" href="javascript:void(0);"><span><?php echo __('Forgot Your Password?') ?></span></a>
                    </div>
                    <div class="primary">
                      <button type="button" class="action btn-social-login" id="bnt-social-login-authentication">
                        <span><?php echo __('Login') ?></span>
                      </button>
                    </div>
                  </div>

                  <?php echo $block->getChildHtml('popup.authentication.social') ?>
                  <p class="create-acnt">
                    <?php echo __( 'Want to create an account?') ?><a class="action create" href="javascript:void(0);"><span><?php /* @escapeNotVerified */ echo __('Sign up now') ?></span></a>
                  </p>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="tab-pane" id="signup">
        <h2>Sign up </h2>

      </div>
    </div>
  </div>
</div>
