<?php
/**
 * Mageplaza_SocialLogin extension
 *                     NOTICE OF LICENSE
 *
 *                     This source file is subject to the MIT License
 *                     that is bundled with this package in the file LICENSE.txt.
 *                     It is also available through the world-wide-web at this URL:
 *                     http://opensource.org/licenses/mit-license.php
 *
 * @category  Mageplaza
 * @package   Mageplaza_SocialLogin
 * @copyright Copyright (c) 2016
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="social-login block-container authentication">
    <div class="tabs-replica">
        <ul>
            <li><a href="#" class="btn-login-form">Login</a></li>
            <li><a href="#" class="btn-register-form">Sign Up</a></li>
        </ul>
    </div>
    <div class="block social-login-customer-authentication">
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form-customer-login"
                  id="social-form-login"
                  data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */
                echo __('* Required Fields') ?>">
                    <p class="login-text">Login now using your My House &amp; Home user account:</p>
                    <div class="field email required">
                        <div class="control">
                            <input name="username"
                                   value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> placeholder="Email *" autocomplete="off"<?php endif; ?>
                                   id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */
                            echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="field password required margintop-20">
                        <div class="control">
                            <input name="password"
                                   type="password" <?php if ($block->isAutocompleteDisabled()) : ?> placeholder="Password *" autocomplete="off"<?php endif; ?>
                                   class="input-text" id="pass" title="<?php /* @escapeNotVerified */
                            echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                    <?php echo $block->getChildHtml('login.captcha') ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="button" class="action login primary" id="bnt-social-login-authentication">
                            <span><?php /* @escapeNotVerified */
                                echo __('Login') ?></span></button>
                        </div>
                        <a class="action remind" href="#"><span><?php /* @escapeNotVerified */
                                    echo __('Forgot Your Password?') ?></span></a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <?php echo $block->getChildHtml('popup.authentication.social') ?>
    <div class="bottom-register">
        <div class="primary popup-register-bottom">
          <a class="create-btn" href="#">Want to create an account ? <span><?php /* @escapeNotVerified */
                echo __('Sign up now') ?></span></a>
        </div>
    </div>
</div>

