<?php
/**
 * Mageplaza_SocialLogin extension
 *                     NOTICE OF LICENSE
 *
 *                     This source file is subject to the MIT License
 *                     that is bundled with this package in the file LICENSE.txt.
 *                     It is also available through the world-wide-web at this URL:
 *                     http://opensource.org/licenses/mit-license.php
 *
 * @category  Mageplaza
 * @package   Mageplaza_SocialLogin
 * @copyright Copyright (c) 2016
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="social-login block-container forgot" style="display:none">
    <div class="forgot-pass-title">
        <h2>Forgot Your Password ?</h2>
        <p>Please enter your email address below to receive a password reset link in your inbox.</p>
    </div>
    <div class="block2 block">
        <div class="block-content2 block-content">
            <form class="form-password-forget"
                  id="social-form-password-forget"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */
                echo __('* Required Fields') ?>">

                    <div class="field email required">
                        <div class="control">
                            <input type="email" name="email" placeholder="Email" alt="email" id="email_address" class="input-text"
                                   value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                    <?php echo $block->getChildHtml('forgot.captcha'); ?>

                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary popup-btn">
                        <button type="button" class="action send"><span><?php /* @escapeNotVerified */
                                echo __('Submit') ?></span></button>
                    </div>
                    <div class="secondary popup-goback">
                        <a class="action back" href="javascript:void(0);"><span><?php /* @escapeNotVerified */
                                echo __('Go back') ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>