<?php
if($block->checkfdrecent()):

$st=$block->getfdstatus();

$allpriority=$st['priority'];
$allstatus=$st['status'];

$allagent = $block->getAvailableAgent();


$domain=$block->getdomain();

$createticketurl=$block->getcreateurl();
$myticketurl=$block->getmyticketurl();
$orderst=$block->checkfdorderid();
?>

<div class="block">
    <div class="block-title ticket">
        <strong>Recent Tickets</strong>
                    <a href="<?php echo $myticketurl; ?>" class="action view">
                <span>View All</span>
            </a>

<a href="<?php echo $createticketurl; ?>" class="action view">
                <span>Create Ticket</span>
            </a>

            </div>
    <div class="block-content">
                <div class="table-wrapper ticket-recent">
            <table id="my-ticket-table" class="data table">
                <caption class="table-caption">Recent Tickets</caption>
                <thead>
                    <tr>
                        <th class="col">Subject</th>
                    <th class="col">Ticket #</th>
                   
                    <th class="col">Date Created</th>                    
 		    <th class="col">Status</th>
                    <th class="col">Agent</th>
<?php if($orderst): ?>
                    <th class="col">Order ID</th> 
<?php endif; ?>
                    <th class="col">Action</th>
                </tr>
                    </tr>
                </thead>
                <tbody>
                        <?php 

$tickets=$block->getRecentTickets();
if(count($tickets)==0){
?>
<td colspan="7">No Tickets</td>
<?php
}
else{

foreach ($tickets as $k=>$ticket): ?>
            <tr>
<td><?php echo $ticket['subject']; ?></td>
                <td><?php echo $k ?></td>
                
                <td><?php echo date('Y-m-d H:i:s',strtotime($ticket['created_at'])) ?></td>
<td><?php echo $allstatus[$ticket['status']] ?></td>
<td><?php if(array_key_exists($ticket['responder_id'],$allagent)){ echo $allagent[$ticket['responder_id']]; }else{ echo "No Agent"; } ?></td>
<?php if($orderst): ?>
<td><a href="<?php echo $ticket['orderurl'] ?>"><?php echo $ticket['order_id'] ?></a></td>
<?php endif; ?>
                <td>
<a href="<?php echo $ticket['url'] ?>"><?php echo "View" ?></a>
</td>
            </tr>
            <?php endforeach;   
}
?>
                                    </tbody>
            </table>
        </div>
        </div>
</div>

<?php
endif;
 ?>



