<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
if (!is_array($fValue)) {
    $fValue = $_hlp->unserializeArr($fValue);
}
$fieldsConfig = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipVendorImport\Helper\Data')->getImportFieldsConfig();
$importFields = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\DropshipVendorImport\Helper\ProtectedCode')->getImportFields();
?>

<div class="grid control">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data admin__control-table" id="<?php echo $this->suffixId('cfgTable')?>" style="width:920px">
        <col width="300" />
        <col width="100" />
        <col width="100" />
        <thead>
        <tr class="headings">
            <th><?php echo __('Field') ?></th>
            <?php /*<th><?php echo __('Default Value') ?></th>*/ ?>
            <th><?php echo __('Sort Order') ?></th>
            <th><?php echo __('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <input name="<?php echo $this->getFieldName()?>[$ROW][field]" value="$FIELD" type="hidden" />
                <h4>$FIELD_NAME</h4>
            </td>
            <?php /*<td>
                <div id="<?php echo $this->getFieldName()?>_$ROW_default_value_container">
                    <select class="<?php echo $this->getFieldName()?>_$ROW_default_value" id="<?php echo $this->getFieldName()?>_$ROW_default_value" multiple="multiple" name="<?php echo $this->getFieldName()?>[$ROW][default_value][]" style="width:100%; height: 200px">
                    </select>

                    <select class="<?php echo $this->getFieldName()?>_$ROW_default_value" id="<?php echo $this->getFieldName()?>_$ROW_default_value_select" name="<?php echo $this->getFieldName()?>[$ROW][default_value]" style="width:100%">
                    </select>

                    <input class="<?php echo $this->getFieldName()?>_$ROW_default_value" id="<?php echo $this->getFieldName()?>_$ROW_default_value_input" name="<?php echo $this->getFieldName()?>[$ROW][default_value]" style="width:200px" />
                    </select>
                </div>
            </td>*/ ?>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:80px" />
            </td>
            <td>
                <button type="button" class="scalable delete delete-fieldset"><span><?php echo __('Remove') ?></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="2" class="a-left">
                <div class="left">
                    <select id="<?php echo $this->suffixId('fields_selector')?>" multiple="multiple" style="height: 200px">
                        <option value=""><?php echo __('* Please select')?></option>
                        <?php if (is_array($fieldsConfig)): foreach ($fieldsConfig as $efc): ?>
                            <optgroup label="<?php echo $this->escapeHtml($efc['label'])?>">
                                <?php if (is_array($efc['value'])): foreach ($efc['value'] as $field): ?>
                                    <option alt="fields_selector" value="<?php echo $field['value']?>"><?php echo $this->escapeHtml($field['label'])?></option>
                                <?php endforeach; endif; ?>
                            </optgroup>
                        <?php endforeach; endif; ?>
                    </select>
                </div>
            </th>
            <th colspan="2" class="a-right">
                <div class="right"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span><?php echo __('Add Fields') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {
var importFieldsJson = <?php echo \Zend\Json\Json::encode($importFields);?>;
var lastRowNum = 0;
var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

function addRow(inData)
{
    var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML;
    var data = {
        field: '',
        field_name: '',
        default_value: '',
        sort_order: '0'
    };
    Object.extend(data, inData);
    if (!importFieldsJson[data.field]) return;
    data.field_name = importFieldsJson[data.field]['label'];
    data.row = ++lastRowNum;

    var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
    var numericVars = ['sort_order'];
    var forcedNumericVars = [];
    var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
    for (j=0; j<keys.length; j++) {
        var i=keys[j];
        value = data[i] || ''
        if (-1 != numericVars.indexOf(i) && data[i]
            || -1 != forcedNumericVars.indexOf(i)
            ) {
            value *= 1;
            data[i] = value;
        }
        if (i!=='row' && isIE) value = '"'+value+'"';
        rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
    }
    var regExTpl = [
        new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
        new Template('<option $1 selected="selected"'),
        new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
        new Template('<input $1 checked="checked"')
    ];
    var selectFields = $H({default_value:1});
    selectFields.each(function(pair){
        var varsForEval, value=data[pair.key], key=pair.key;
        for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
            varsForEval = [];
            if (pair.value) {
                if (!Object.isArray(value)) {
                    value = String.interpret(value).split(',');
                }
                value.each(function(val){
                    varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(val)});
                })
            } else {
                varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(value)});
            }
            for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                var varForEval = varsForEval[vfeIdx];
                var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
            }
        }
    });
    tbody.insert('<tr>'+rowHtml+'</tr>');
    //initDefaultValue(data);
    var trs = tbody.childElements()
    var tr = trs[trs.length-1]
    tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
    var del = $(tr).select('button.delete-fieldset')[0];
    if (del) {
        $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
    }
}

$('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) {
    e.stop();
    $$('#<?php echo $this->suffixId('fields_selector')?> option').each(function(el) {
        if (el.selected && el.value && importFieldsJson[el.value]) {
            addRow({field: el.value});
        }
        el.selected = false;
    });
});

<?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
addRow(<?php echo \Zend\Json\Json::encode($fV) ?>);
<?php endforeach; endif; ?>
});
</script>