<?php
/**
 * Awe Menu is quick, easy to setup and WYSIWYG menu management system
 *
 * Awe Menu by Kahanit(https://www.kahanit.com) is licensed under a
 * Creative Creative Commons Attribution-NoDerivatives 4.0 International License.
 * Based on a work at https://www.kahanit.com.
 * Permissions beyond the scope of this license may be available at https://www.kahanit.com.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nd/4.0/.
 *
 * @author    Amit Sidhpura <amit@kahanit.com>
 * @copyright 2016 Kahanit
 * @license   http://creativecommons.org/licenses/by-nd/4.0/
 * @version   1.0.1.0
 */
?>

<div class="wrap">
    <div id="am-builder" data-mage-init='<?= $block->aweMenuMageInit(); ?>'>
        <div class="bootstrap">
            <?php include "panels/editor.phtml"; ?>
            <?php include "panels/revisions.phtml"; ?>
            <?php include "configurations/row.phtml"; ?>
            <?php include "configurations/column.phtml"; ?>
            <?php include "configurations/item.phtml"; ?>
            <div class="module-text">Awe Menu - Magento Mega Menu Module (v1.0.1)</div>
        </div>
    </div>
</div>