<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('contact-info')
          ->toHtml();
?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">

    <h3>Contact Form</h3>
    <div class="row marginbottom-30">
        <div class="col-md-6 col-sm-6">
            <div class="field name required">
                <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Full Name') ?></span>
                <span class="asterix">*</span>
                </label>
                <div class="control">
                    <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>
        <div class="field email col-md-6  col-sm-6 required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
            <span class="asterix">*</span>
            </label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </div>

    <div class="row marginbottom-30">
        <div class="field col-md-6 col-sm-6 telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?> <span class="lowercase">(not required)</span></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field order-number col-md-6 col-sm-6">
            <label class="label" for="order-number"><span>Order Number <span class="lowercase">(if applicable)</span></span></label>
            <div class="control">
                <input name="order-number" id="order-number" title="<?php /* @escapeNotVerified */ echo __('Order Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('order-number')) ?>" class="input-text" type="text" />
            </div>
        </div>
    </div>

    <div class="row marginbottom-30">
        <div class="field subject col-md-6 col-sm-6">
            <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?></span>
            <span class="asterix">*</span>
            </label>
            <div class="control">
                <div class="styled-select">
                <select name="subject" id="subject" data-validate="{required:true}">
                    <option value="">Please choose one</option>
                    <option value="product"><?php echo __('Product Information') ?></option>
                    <option value="order"><?php echo __('Orders') ?></option>
                    <option value="shipping"><?php echo __('Shipping & Delivery') ?></option>
                    <option value="return"><?php echo __('Exchange & Returns') ?></option>
                    <option value="feedback"><?php echo __('Feedback & Suggestions') ?></option>
                    <option value="others"><?php echo __('Others') ?></option>
                </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>


        <div class="field comment required">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span>
            <span class="asterix">*</span>
            </label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
            </button>
        </div>
    </div>
    <p class="required-msg"><span class="asterix">*</span> Required Fields</p>
</form>