<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="checkout-success-actions">
  <?php if (true) :?>
      <?php /* @escapeNotVerified */ echo __('<a href="%1" onclick="this.target=\'_blank\'" class="print action primary">Print Order Details</a>', $block->getPrintUrl()) ?>
      <?php echo $block->getChildHtml() ?>
  <?php endif;?>

  <a class="checkout-success-continue hover-effect" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>">
    <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
  </a>
</div>
