<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php $helper = $this->helper('Hhmedia\Override\Helper\Override'); ?>
<?php $proHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
<?php $orderDetail = $helper->getOrderDetails($block->getOrderId()); ?>
<?php $billingAddress = $orderDetail->getBillingAddress()->getData(); ?>
<?php $shippingAddress = $orderDetail->getShippingAddress()->getData(); ?>
<?php $_items = $orderDetail->getAllVisibleItems(); ?>

<div class="checkout-success">
  <div class="checkout-success-header">
      <?php if ($block->getOrderId()):?>
            <p><?php /* @escapeNotVerified */ echo __('Your order has been confirmed.') ?></p>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order number is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>
  </div>

  <div class="order-summary">
    <div class="block block-dashboard-addresses">
      <div class="block-title">
        Order Summary
      </div>
      <div class="block-content row">
        <div class="box col-md-6">
          <span class="box-title">Shipping Address:</span>
          <div class="box-content">
            <p><?php echo $shippingAddress['firstname'].' '.$shippingAddress['lastname']; ?></p>
            <p><?php echo $shippingAddress['street']; ?></p>
            <p><?php echo $shippingAddress['city'].', '.$shippingAddress['region']; ?></p>
            <p><?php if($shippingAddress['country_id'] == 'CA'){ echo "Canada"; }else{ echo "United States"; } ?></p>
            <p><?php echo $shippingAddress['telephone']; ?></p>
          </div>
        </div>
        <div class="box col-md-6">
          <span class="box-title">Billing Address:</span>
          <div class="box-content">
            <p><?php echo $billingAddress['firstname'].' '.$billingAddress['lastname']; ?></p>
            <p><?php echo $billingAddress['street']; ?></p>
            <p><?php echo $billingAddress['city'].', '.$billingAddress['region']; ?></p>
            <p><?php if($billingAddress['country_id'] == 'CA'){ echo "Canada"; }else{ echo "United States"; } ?></p>
            <p><?php echo $billingAddress['telephone']; ?></p>
          </div>
        </div>
      </div>

    </div>
    <div class="block">
      <div class="box-title">
        <?php echo count($_items).' items purchased:'; ?>
      </div>
      <div class="block-content order-products">
        <?php foreach ($_items as $_item): ?>

          <?php $product = $helper->getProductBySku($_item->getSku()); ?>
          <?php $image = $product->getData('thumbnail'); ?>
          <?php $qty = $_item->getQtyOrdered(); ?>
          <?php $productOptions = $_item->getProductOptions(); ?>

          <div class="row">
            <div class="col-md-6">
              <img src="<?php echo $proHelper->resize($image,80,80); ?>" />
              <div class="order-product-details">
                <span class="order-product-name"><?php echo $product->getName() ?></span>
                <div class="order-product-options">
                  <?php 
                    foreach($productOptions as $key => $val):
                      if($key == 'attributes_info'):
                        foreach($val as $attribute):
                          echo "<span class='product-option'>", $attribute['value'], "</span>";
                        endforeach;
                      endif;
                    endforeach;
                  ?>
                  <span><?php echo 'Qty: '.($qty)*1; ?></span>
                  <span class="sku"><?php echo 'SKU# '.$_item->getSku() ?></span>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <span class="order-product-price"><?php echo ($_item->getPrice())*$qty*1; ?></span>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
  <div class="checkout-success-totals">
    <div class="totals-wrapper">
      <div class="price-row">
        <span class="price-label">Subtotal</span> <span class="price"><?php echo ($orderDetail->getSubTotal())*1; ?></span>
      </div>
      <div class="price-row">
        <span class="price-label">Shipping</span><span class="price"><?php echo ($orderDetail->getShippingAmount())*1; ?></span>
      </div>
      <div class="price-row">
        <span class="price-label">Taxes</span><span class="price"><?php echo ($orderDetail->getTaxAmount())*1; ?></span>
      </div>
      <div class="price-row">
        <span class="price-label">Total</span><span class="price grand-total"><?php echo ($orderDetail->getGrandTotal())*1; ?></span>
      </div>
    </div>
    <div class="payment-method">
      <p>Payment Method</p>
      <span class="card">VISA 0124</span><span class="price"><?php echo ($orderDetail->getGrandTotal())*1; ?></span>
    </div>
  </div>
</div>
