<?php
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
if (!$_hlp->isModuleActive('Unirgy_DropshipTierShipping')) return;
$_tsHlp = $_hlp->getObj('Unirgy\DropshipTierShipping\Helper\Data');
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
/** @var \Unirgy\Dropship\Helper\Data $_hlp */
$_hlp = \Magento\Framework\App\ObjectManager::getInstance()->get('Unirgy\Dropship\Helper\Data');
if (!is_array($fValue)) {
    $fValue = $_hlp->unserializeArr($fValue);
}
$cShipClass = $_hlp->getObj('Unirgy\DropshipShippingClass\Model\Source')->setPath('customer_ship_class')->toOptionHash();
$deliveryTypes = $_hlp->getObj('Unirgy\DropshipTierShipping\Model\ResourceModel\DeliveryType\Collection')->toOptionHash();
$conditions = $_hlp->getObj('Unirgy\DropshipTierShipping\Model\Source')->setPath('simple_condition')->toOptionHash();
$escaper = $_hlp->getObj('\Magento\Framework\Escaper');
?>

<div class="grid control">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data admin__control-table" id="<?php echo $this->suffixId('cfgTable')?>" style="width:920px">
        <col width="150" />
        <col width="150" />
        <col width="150" />
        <col width="200" />
        <col width="100" />
        <col width="100" />
        <thead>
        <tr class="headings">
            <th><?php echo __('Column') ?></th>
            <th><?php echo __('Delivery Type') ?></th>
            <th><?php echo __('Customer') ?></th>
            <th><?php echo __('Condition') ?></th>
            <th><?php echo __('Sort Order') ?></th>
            <th><?php echo __('Action') ?></th>
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <input name="<?php echo $this->getFieldName()?>[$ROW][column]" value="$COLUMN" type="hidden" />
                <h4>$COLUMN_NAME</h4>
            </td>
            <td>
                <div id="<?php echo $this->getFieldName()?>_$ROW_delivery_container">
                <select name="<?php echo $this->getFieldName()?>[$ROW][delivery_type_id]" style="width:150px">
                    <?php foreach ($deliveryTypes as $dtId=>$dtLabel): ?>
                        <option alt="delivery_type_id" value="<?php echo $dtId?>"><?php echo $this->escapeHtml($dtLabel)?></option>
                    <?php endforeach; ?>
                </select>
                </div>
            </td>
            <td>
                <div id="<?php echo $this->getFieldName()?>_$ROW_customer_container">
                    <select multiple="multiple" name="<?php echo $this->getFieldName()?>[$ROW][customer_shipclass_id][]" style="width:150px; height: 150px">
                        <option alt="customer_shipclass_id" value="*"><?php echo __('*** All ***')?></option>
                        <?php foreach ($cShipClass as $cscId=>$cscLabel): ?>
                            <option alt="customer_shipclass_id" value="<?php echo $cscId?>"><?php echo $this->escapeHtml($cscLabel)?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </td>
            <td>
                <div id="<?php echo $this->getFieldName()?>_$ROW_conditions_container">
                    <label style="width: 150px"><?php echo __('Condition Name') ?></label>&nbsp;&nbsp;
                    <select  style="width: 150px" name="<?php echo $this->getFieldName()?>[$ROW][condition_name]">
                        <option value=""><?php echo __('* Please select')?></option>
                        <?php foreach ($conditions as $_cKey=>$_cValue): ?>
                            <option alt="condition_name" value="<?php echo $_cKey?>"><?php echo $this->escapeHtml($_cValue)?></option>
                        <?php endforeach; ?>
                    </select>
                    <br />
                    <label style="width: 150px"><?php echo __('If Condition Up To') ?></label>&nbsp;&nbsp;
                    <input name="<?php echo $this->getFieldName()?>[$ROW][condition_to]" value="$CONDITION_TO" type="text" />
                    <br />
                    <label style="width: 150px"><?php echo __('Rate Sort Order') ?></label>&nbsp;&nbsp;
                    <input name="<?php echo $this->getFieldName()?>[$ROW][rate_sort_order]" value="$RATE_SORT_ORDER" type="text" />
                </div>
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:80px" />
            </td>
            <td>
                <button type="button" class="scalable delete delete-fieldset"><span><?php echo __('Remove') ?></span></button>
            </td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th colspan="2" class="a-left">
                <div class="left">
                    <select id="<?php echo $this->suffixId('column_selector')?>" multiple="multiple" style="height: 200px">
                        <option value=""><?php echo __('* Please select')?></option>
                        <option alt="column_selector" value="vendor_name"><?php echo __('Vendor Name')?></option>
                        <option alt="column_selector" value="cost"><?php echo __('Price Column')?></option>
                    </select>
                </div>
            </th>
            <th colspan="2" class="a-right">
                <div class="right"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span><?php echo __('Add Columns') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
require(["jquery", "prototype"], function(jQuery) {
var columnNames = {
    vendor_name: '<?php echo $escaper->escapeJsQuote(__('Vendor Name'))?>',
    cost: '<?php echo $escaper->escapeJsQuote(__('Price Column'))?>'
};
var lastRowNum = 0;
var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

function addRow(inData)
{
    var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
    var data = {
        column: '',
        column_name: '',
        delivery_type_id: '',
        customer_shipclass_id: '',
        condition_name: '',
        condition_to: '0',
        rate_sort_order: '0',
        sort_order: '0'
    }
    Object.extend(data, inData);
    data.column_name = columnNames[data.column];
    data.row = ++lastRowNum;

    var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
    var numericVars = ['sort_order','condition_to','rate_sort_order'];
    var forcedNumericVars = [];
    var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
    for (j=0; j<keys.length; j++) {
        var i=keys[j];
        value = data[i] || ''
        if (-1 != numericVars.indexOf(i) && data[i]
            || -1 != forcedNumericVars.indexOf(i)
            ) {
            value *= 1;
            data[i] = value;
        }
        if (i!=='row' && isIE) value = '"'+value+'"';
        rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
    }
    var regExTpl = [
        new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
        new Template('<option $1 selected="selected"'),
        new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
        new Template('<input $1 checked="checked"')
    ];
    var selectFields = $H({delivery_type_id:0,customer_shipclass_id:1,condition_name:0});
    selectFields.each(function(pair){
        var varsForEval, value=data[pair.key], key=pair.key;
        for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
            varsForEval = [];
            if (pair.value) {
                if (!Object.isArray(value)) {
                    value = String.interpret(value).split(',');
                }
                value.each(function(val){
                    varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(val)});
                })
            } else {
                varsForEval.push({key: RegExp.escape(key), value: RegExp.escape(value)});
            }
            for (var vfeIdx=0; vfeIdx<varsForEval.length; vfeIdx++) {
                var varForEval = varsForEval[vfeIdx];
                var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
            }
        }
    });
    tbody.insert('<tr>'+rowHtml+'</tr>');
    if (data.column=='vendor_name') {
        $('<?php echo $this->getFieldName()?>_'+data.row+'_delivery_container').hide();
        $('<?php echo $this->getFieldName()?>_'+data.row+'_customer_container').hide();
        $('<?php echo $this->getFieldName()?>_'+data.row+'_conditions_container').hide();
    }
    //initDefaultValue(data);
    var trs = tbody.childElements()
    var tr = trs[trs.length-1]
    tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
    var del = $(tr).select('button.delete-fieldset')[0];
    if (del) {
        $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
    }
}

$('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) {
    e.stop();
    $$('#<?php echo $this->suffixId('column_selector')?> option').each(function(el) {
        if (el.selected && el.value) {
            addRow({column: el.value});
        }
        //el.selected = false;
    });
});

<?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
addRow(<?php echo \Zend\Json\Json::encode($fV) ?>);
<?php endforeach; endif; ?>
});
</script>