  <?php
  /**
   * Copyright © 2016 Magento. All rights reserved.
   * See COPYING.txt for license details.
   */

  // @codingStandardsIgnoreFile

  ?>
  <?php if ($crumbs && is_array($crumbs)) : ?>

<section class="main-breadcrumb">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
                <?php if ($crumbInfo['link']) : ?>
                    <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                        <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                    </a>
                <?php elseif ($crumbInfo['last']) : ?>
                    <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                <?php else: ?>
                    <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
        <?php endif; ?>
      </div>
    </div>
  </div>
</section>