<h4 class="subtitle"><?php echo __('Vancouver Design Star Curates her favorite items for spring - Just For Us'); ?></h4>
<?php if ($this->getGuestEditor()->getSize()): ?>
<div class="guest-editor-top">
    <div class="row">
    <div class="vcenter-flex display-block-xs">
    <?php foreach($this->getGuestEditor() as $guest): ?>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 editor-guest-image" style="background-image:url(<?php echo $this->getUrl('pub/media').$guest->getImage() ?>)"></div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 guest-editor vcenter-flex" style="background-color:<?php echo $guest->getColor() ?>">
            <div class="guest-editor-details vcenter vcenter-col">
                <h3 class="guest-name"><a href="<?php echo $this->getItemUrl($guest) ?>"><?php echo $guest->getName(); ?></a></h3>
                <h4 class="guest-job"><?php echo $guest->getJobTitle(); ?></h4>
                <div class="editor-blurb"><?php echo $guest->getContent(); ?></div>
                <!--<div class="editor-quote"><?php echo $guest->getShortQuote(); ?></div>-->
                <a href="<?php echo $this->getItemUrl($guest) ?>" class="btn btn-main btn-picks">See Picks</a>
            </div>
        </div>
    <?php break; endforeach; ?>
    </div>
    </div>
</div>
<?php endif; ?>
<?php 
$pastEditor = $this->getCollection()
            ->addFieldToFilter('past', 1)
            ->addFieldToFilter('guest',0);   
?>
<?php if ($pastEditor->getSize()): ?>
<div class="editor_list_view">
    <h2 class="page-title fancyfont"><span><?php echo __("H&H Editors' Picks") ?></span></h2>
    <h4 class="subtitle"><?php echo __('See What your favorite editors have selected and why'); ?></h4>
    <?php foreach ($pastEditor as $editorItem): ?>
        <div id="item_<?php echo $editorItem->getId() ?>" class="col-md-3 col-sm-3 col-xs-6 editor_list_item">
            <a href="<?php echo $this->getItemUrl($editorItem) ?>">
                <img src="<?php echo $this->getUrl('pub/media').$editorItem->getImage() ?>" alt="<?php echo $this->escapeHtml($editorItem->getName()); ?>" />
            </a>
            <h4>
                <a href="<?php echo $this->getItemUrl($editorItem) ?>" class="hover-effect">
                <?php echo $this->escapeHtml($editorItem->getName()) ?>
                </a>
            </h4>
            <h5><?php echo $this->escapeHtml($editorItem->getJobTitle()) ?></h5>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Editor.'); ?></span></div>
<?php endif ?>
