<div class="row">
    <div class="col-md-12">
        <a href="<?php echo $this->getBackUrl() ?>" class="editor-link editor-back hover-effect">&lt; All Editors</a>
    </div>
</div>
<?php $_editorItem = $this->getEditor(); ?>

<div class="row">
    <div class="col-md-7 col-md-offset-3">
    <div class="vcenter vcenter-column editor-intro">
        <div class="editor-img">
            <img src="<?php echo $this->getUrl('pub/media').$_editorItem->getImage() ?>" alt="<?php echo $this->escapeHtml($_editorItem->getName()); ?>" />
        </div>
        <div class="editor-details">
            <?php if($_editorItem->getSubtitle() != ''): ?>
                <div class="editor-guest-title"><?php echo $_editorItem->getSubtitle(); ?></div>
            <?php endif; ?>
            <div class="editor-name"><?php echo $this->escapeHtml($_editorItem->getName()) ?></div>
            <div class="editor-job"><?php echo $this->escapeHtml($_editorItem->getJobTitle()) ?></div>
        </div>
    </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="text-center editor-quote">
            <div class="quote"><?php echo $_editorItem->getQuote() ?></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-6 col-md-offset-3 editor-bio">
        <h4>Biography</h4>
        <?php echo $_editorItem->getBio() ?>
    </div>
</div>


<div class="editor_item_view">
    <div class="row editor-products">
        <?php
            $products = $this->getProductCollection();
            foreach($products as $_product):
            $pro = $this->getProductData($_product);
            $image = $pro->getData('small_image');
        ?>
        <li class="col-md-3 editor-product">
            <div class="editor-product-img relative">
                <a href="<?php echo $pro->getProductUrl() ?>">
                    <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" />
                </a>
                <?php $quickViewUrl = $this->getUrl('').'weltpixel_quickview/catalog_product/view/id/'.$pro->getId(); ?>
                <a href="javascript: void(0);" data-quickview-url="<?php echo $quickViewUrl ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
            </div>
            <h4>
                <a class="hover-effect" href="<?php echo $pro->getProductUrl() ?>"><?php echo $pro->getName(); ?></a>
            </h4>
            <?php $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct'); ?>
            <h5 class="decorating-formula-price"><?php echo $abstractProductBlock->getProductPrice($pro) ?></h5>

            <div class="editor-mini-quote"><?php echo $pro->getData('editors_quote'); ?></div>
        </li>
        <?php endforeach; ?>
    </div>
</div>

<div class="editors-thumbs">
    <h2 class="page-title marginbottom-40"><span><?php echo __("More Editors") ?></span></h2>
    <?php $objEditor = $block->getLayout()->createBlock('Hhmedia\Editor\Block\Editor'); ?>
    <?php $_editor = $objEditor->getCollection()->addFieldToFilter('past', 1)->addFieldToFilter('guest',0)->setPageSize(4); ?>
    <?php $_editor->getSelect()->orderRand(); ?>
    <div class="row">
        <?php foreach($_editor as $editor): ?>
            <?php if($editor->getEditorId() != $this->getRequest()->getParam('id')): ?>
                <div class="col-md-3 editor-single-thumb text-center">
                    <a href="<?php echo $objEditor->getItemUrl($editor) ?>">
                        <img src="<?php echo $this->getUrl('pub/media').$editor->getImage() ?>" alt="<?php echo $this->escapeHtml($editor->getName()); ?>" />
                        <h4><?php echo $this->escapeHtml($editor->getName()) ?></h4>
                    <h5><?php echo $this->escapeHtml($editor->getJobTitle()) ?></h5>
                    </a>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="<?php echo $this->getBackUrl() ?>" class="editor-link view-all-editors hover-effect">View All Editors &gt;</a>
        </div>
    </div>
</div>