<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Review\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>


<div class="row review-topbar">
    <div class="col-md-12">
        <div class="block-main-title nomargin-bottom">Product Review History</div>
    </div>
    <div class="clearfix"></div>
</div>

<?php foreach ($block->getReviews() as $_review): ?>
<div class="account-reviews-listing">
    <div class="row">
        <div class="col-md-12">
            <h4>
                <?php echo $block->dateFormat($_review->getReviewCreatedAt()); ?>
                <span>
                    <?php
                        if($_review->getStatusId() == 1){
                            echo "Review Approved";
                        }elseif($_review->getStatusId() == 2){
                            echo "Review Pending";
                        }else{
                            echo "Review Declined";
                        }
                    ?>
                </span>
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 review-product-img">
            <?php $helper = $this->helper('Hhmedia\Override\Helper\Override'); ?>
            <?php $product = $helper->getLoadProduct($_review->getEntityPkValue()); ?>
            <?php $image = $product->getData('small_image'); ?>
            <a href="<?php echo $block->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>">
                <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" class="product-image" />
            </a>
        </div>
        <div class="col-md-9 review-product-details">
            <div class="product-title">
                <a href="<?php echo $block->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>">
                    <?php echo $block->escapeHtml($_review->getName()) ?>
                </a>
                <div class="ratings">
                    <?php if ($_review->getSum()): ?>
                        <div class="rating-summary">
                            <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
                            <div class="rating-result" title="<?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%">
                                <span style="width:<?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%;"><span><?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%</span></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="desc">
                    <?php echo $_review->getDetail() ?>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<?php endforeach; ?>




    <div class="table-wrapper reviews" style="display: none;">
        <table class="data table table-reviews" id="my-reviews-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Product Review History') ?></caption>
            <thead>
                <!--<tr>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Created') ?></th>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th scope="col" class="col summary"><?php /* @escapeNotVerified */ echo __('Rating') ?></th>
                    <th scope="col" class="col description"><?php /* @escapeNotVerified */ echo __('Review') ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>-->
            </thead>
            <tbody>
                <?php foreach ($block->getReviews() as $_review): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Created')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->dateFormat($_review->getReviewCreatedAt()); ?>
                    <?php
                    if($_review->getStatusId() == 1){
                        echo "Review Approved";
                    }elseif($_review->getStatusId() == 2){
                        echo "Review Pending";
                    }else{
                        echo "Review Declined";
                    }
                    ?>
                    </td>

                    <td data-th="<?php echo $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <?php $helper = $this->helper('Hhmedia\Override\Helper\Override'); ?>
                        <?php $product = $helper->getLoadProduct($_review->getEntityPkValue()); ?>
                        <?php $image = $product->getData('small_image'); ?>
                        <a href="<?php echo $block->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>">
                        <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" class="product-image" />
                        </a>
                        <a href="<?php echo $block->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>">
                            <?php echo $block->escapeHtml($_review->getName()) ?>
                        </a>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Rating')) ?>" class="col summary">
                    <?php if ($_review->getSum()): ?>
                        <div class="rating-summary">
                            <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
                            <div class="rating-result" title="<?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%">
                                <span style="width:<?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%;"><span><?php /* @escapeNotVerified */ echo($_review->getSum() / $_review->getCount()) ?>%</span></span>
                            </div>
                        </div>
                    <?php endif; ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Review')) ?>" class="col description">
                        <?php echo $_review->getDetail() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <!--<a href="<?php /* @escapeNotVerified */ echo $block->getReviewLink() ?>id/<?php /* @escapeNotVerified */ echo $_review->getReviewId() ?>" class="action more">
                            <span><?php /* @escapeNotVerified */ echo __('See Details') ?></span>
                        </a>-->
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>


    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom none">
            <?php echo $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have not reviewed any products. Check out your past orders and start reviewing your favorite products.') ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Back') ?></span>
        </a>
    </div>
</div>
