<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>

<div class="row cart-item">
  <div class="col-md-3 col-sm-4 col-xs-3">
    <?php if ($block->hasProductUrl()):?>
    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
      title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
      tabindex="-1"
      class="product-item-photo">
      <?php else:?>
      <span>
        <?php endif;?>
        <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
        <?php if ($block->hasProductUrl()):?>
      </a>
      <?php else: ?>
    </span>
    <?php endif; ?>
  </div>
  <div class="col-md-9 col-sm-8 col-xs-9">
    <div class="row">
      <div class="col-md-5 col-sm-12 col-xs-12 cart-item-name-container">
        <?php if ($block->hasProductUrl()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>" class="cart-item-name"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
        <?php else: ?>
        <span class="cart-item-name">
          <?php echo $block->escapeHtml($block->getProductName()) ?>
        </span>
        <?php endif; ?>

      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <div class="cart-qty-wrapper">
          <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
            <span><?php /* @escapeNotVerified */ echo __('Qty:') ?></span>
          </label>
          <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
          name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
          data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
          value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
          type="number"
          size="4"
          title="<?php echo $block->escapeHtml(__('Qty')); ?>"
          class="input-text cart-item-qty"
          maxlength="12"
          data-validate="{required:true,'validate-greater-than-zero':true}"
          data-role="cart-item-qty"/>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <?php if ($canApplyMsrp): ?>
        <span class="cart msrp subtotal">--</span>
        <?php else: ?>
        <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
        <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
        <a href="#"
           title="<?php echo $block->escapeHtml(__('Remove item')); ?>"
           class="action action-delete cart-item-remove"
           data-post='<?php echo $customHelper->getItemDeleteUrl($_item); ?>'>
            ╳
        </a>
      </div>
    </div>
    <div class="row cart-details-container">
      <span class="cart-item-details">
        <?php if ($canApplyMsrp): ?>
        <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
        <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
          <?php /* @escapeNotVerified */ echo __("What's this?"); ?>
        </a>
        <?php else: ?>
        <span><?php echo $product->getFinalPrice(); ?> ea.</span>
        <?php endif; ?>
        <?php if ($_options = $block->getOptionList()):?>
        <?php foreach ($_options as $_option) : ?>
        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
        <span>
          <?php if (isset($_formatedOptionValue['full_view'])): ?>
          <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
          <?php else: ?>
          <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
          <?php endif; ?>
        </span>
        <?php endforeach; ?>
        <?php endif;?>
      </span>
      <span class="cart-item-sku">
        SKU: <?php /* @escapeNotVerified */ echo $_item->getSku() ?>
      </span>
      <span class="cart-item-shipping">
        Ships in approximately 10 business days*
      </span>
      <div class="cart-item-actions">
        <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
      </div>

    </div>
  </div>
</div>