<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <?php 
            $obj = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $obj->get('Magento\Customer\Model\Session'); 
            $firstName = $customerSession->getCustomer()->getFirstname();
            $lastName = $customerSession->getCustomer()->getLastname();
        ?>
        <a href="<?php echo $this->getUrl('customer/account'); ?>">
        	<span class="customer-name"><?php echo $firstName.' '.$lastName[0]; ?></span>
    	</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('customer/account'); ?>">
            <?php echo __('My Account') ?>
        </a>
<?php endif; ?>