<?php $helper = $this->helper('Altima\Lookbookslider\Helper\Data'); ?>
<?php $sliderCollection = $this->getCollection('content-top'); ?>
<?php
	foreach($sliderCollection as $slider):
		$sliderId = $slider->getSliderId();
		break;
 	endforeach;
?>
<?php
	$blockObj= $block->getLayout()->createBlock('Altima\Lookbookslider\Block\SliderItem');
	$shotCollection =  $blockObj->getShotCollection($sliderId);
?>

<h2 class="page-title basefont"><span><strong class="dietdidot">Shop</strong> MORE SHOTS</span></h2>
<h4 class="subtitle"><?php echo __('Inspiration for every room in the house') ?></h4>

<div class="row no-gutters marginbottom-50">
<?php foreach($shotCollection as $shot): ?>
	<?php $slideId = $shot->getSlideId(); ?>
	<?php $imagePath = $helper->getResizedUrl($shot->getImagePath(),'400','400'); ?>
	<div class="col-md-3 col-sm-6 col-xs-6">
		<div class="shot-thumb">
			<a href="<?php echo $this->getUrl('lookbookslider/index/view').'?slider_id='.$sliderId.'&slide_id='.$slideId; ?>">
				<img src="<?php echo $imagePath; ?>" />
				<div class="shot-thumb-meta">
					<h4><span>Shop</span></h4>
					<span class="title" style="color:<?php echo $shot->getColor() ?>"><?php echo $shot->getTitle(); ?></span>
				</div>
			</a>
		</div>
	</div>
<?php endforeach; ?>
</div>