<?php $helper = $this->helper('Altima\Lookbookslider\Helper\Data'); ?>
<?php $sliderCollection = $this->getCollection('content-top'); ?>
<?php
	foreach($sliderCollection as $slider):
		$sliderId = $slider->getSliderId();
		break;
 	endforeach;
?>
<?php
	$blockObj= $block->getLayout()->createBlock('Altima\Lookbookslider\Block\SliderItem');
	$shotCollection =  $blockObj->getShotCollection($sliderId);
?>

<div class="row no-gutter">
<?php foreach($shotCollection as $shot): ?>
	<?php $slideId = $shot->getSlideId(); ?>
	<?php $imagePath = $helper->getResizedUrl($shot->getImagePath(),'400','400'); ?>
	<div class="col-md-3">
		<div class="shot-thumb">
			<a href="<?php echo $this->getUrl('lookbookslider/index/view').'?slider_id='.$sliderId.'&slide_id='.$slideId; ?>">
				<img src="<?php echo $imagePath; ?>" />
				<div class="shot-thumb-meta">
					<h4><span>Shop</span></h4>
					<span class="title green"><?php echo $shot->getTitle(); ?></span>
				</div>
			</a>
		</div>
	</div>
<?php endforeach; ?>
</div>