<?php $availableSocials = $this->getAvailableSocials(); ?>
<?php if (sizeof($availableSocials)): ?>
<div class="block social-login-authentication-channel col-mg mg-5">
    <div class="block-title">
        <?php echo __('Or') ?>
    </div>
    <div class="block-content">
        <?php foreach ($availableSocials as $key => $social): ?>
			<div class="actions-toolbar social-btn <?= $key ?>-login">
                <div class="primary">
                    <button class="action btn_<?= $key ?>_signup" id="btn_<?= $key ?>_signup" type="button">
                        <span>
                            <span><?php echo __('Sign Up with %1', $social->getLabel()) ?></span>
                        </span>
                    </button>
                </div>
            </div>
			<script>
                require(['jquery', 'Mageplaza_SocialLogin/js/sociallogin'], function ($, SocialLoginPopup) {
					$('#btn_<?= $key ?>_signup').click(function () {
						var popup = new SocialLoginPopup();
						popup.openPopup('<?php echo $social->getLoginUrl()?>', '<?php echo __('Sign Up By %1', $social->getLabel())?>');
					});
				});
            </script>
		<?php endforeach; ?>
    </div>
</div>
<?php endif; ?>