<?php $availableSocials = $this->getAvailableSocials(); ?>
<?php if (sizeof($availableSocials)): ?>
<div class="block social-login-authentication-channel">
    <div class="block-title or-separator">
        <span><?php echo __('Or') ?></span>
    </div>
    <div class="block-content">
        <ul>
        <?php foreach ($availableSocials as $key => $social): ?>
            <li>
			<div class="actions-toolbar social-btn <?= $key ?>-login">
                <div class="primary">
                    <button class="action btn_<?= $key ?>_login" id="btn_<?= $key ?>_login" type="button">
                        <span>
                            <span><?php echo __('Login with %1', $social->getLabel()) ?></span>
                        </span>
                    </button>
                </div>
            </div>
			<script>
                require(['jquery', 'Mageplaza_SocialLogin/js/sociallogin'], function ($, SocialLoginPopup) {
					$('#btn_<?= $key ?>_login').click(function () {
						var popup = new SocialLoginPopup();
						popup.openPopup('<?php echo $social->getLoginUrl()?>', '<?php echo __('Login By %1', $social->getLabel())?>');
					});
				});
            </script>
            </li>
		<?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>

