<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
  <div class="single-product-cart">
    <?php if ($block->shouldRenderQuantity()): ?>
    <div class="product-qty">
      <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
      <input type="number"
             name="qty"
             id="qty"
             maxlength="12"
             value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
             title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
             data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
         />
      </div>
    </div>
    <?php endif; ?>
    <div class="actions">
      <button type="submit"
              title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
              class="action btn-cart-single btn-main"
              id="product-addtocart-button">
        <span><i class="mdi mdi-cart-outline"></i><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
      </button>
      <?php echo $block->getChildHtml('', true) ?>
    </div>
  </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>