<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
  <div class="single-product-cart">
    <?php if ($block->shouldRenderQuantity()): ?>

    <div class="product-qty">
      <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
      <div class="styled-select">
      <!--<input type="number"
             name="qty"
             id="qty"
             maxlength="12"
             value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
             title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
             data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
         />-->
         <select class="input-text qty-select" name="qty" id="qty">
          <?php for($i=1; $i<=40; $i++){ ?>
            <option value="<?php echo $i ?>">
              <?php echo $i?>
            </option>
          <?php } ?>
        </select>
        </div>
      </div>

    </div>
    <?php endif; ?>
    <div class="actions">
      <button type="submit"
              title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
              class="action tocart btn-cart-single btn-main"
              id="product-addtocart-button">
              <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
      </button>
      <?php echo $block->getChildHtml('', true) ?>
    </div>
  </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function () {
            'use strict';
            var validationErrorMoved = false;
            $('#product-addtocart-button').click(function() {
                if (!validationErrorMoved) {
                    $('.swatch-attribute').each(function() {
                        var attrId = $(this).attr('attribute-id');
                        var validationElement = $('input[name="super_attribute['+attrId+']"]').get(0);
                        $(validationElement).appendTo(this);
                    });
                    validationErrorMoved = true;
                }
            });
        });
    });
</script>
