<?php 
if(trim($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getFinalSale(), 'final_sale')) != '' && trim($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getFinalSale(), 'final_sale')) != 'N' && trim($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getFinalSale(), 'final_sale')) != 'No')
	echo 'This item has a restocking fee of ' . $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getRestockingFee(), 'restocking_fee').'<br />';
switch($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getFinalSale(), 'final_sale')) {
	case 'Y':
	case '1':
	case 'Yes':
		echo 'This item is final sale <br />';
}
switch($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getCallForQuote(), 'call_for_quote')) {
        case 'Y':
        case '1':
        case 'Yes':
                echo 'This item is call for quote <br />';
}
switch($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getReturnable(), 'returnable')) {
        case 'Y':
	case '1':
        case 'Yes':
                echo 'This item is returnable <br />';
}
switch($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getShippableUsa(), 'shippable_usa')) {
        case 'Y':
	case '1':
        case 'Yes':
                echo 'This item is shippable to the US <br />';
}
if(trim($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getShippingDelivery(), 'shipping_delivery')) != '')
	echo 'This product ships from '.$this->helper('Unirgy\Dropship\Helper\Data')->getVendorName($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getUdropshipVendor(), 'udropship_vendor')). ' within '.strip_tags($this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getShippingDelivery(), 'shipping_delivery')); 

?>
