<?php $_product = $block->getProduct(); ?>
<?php $helper = $this->helper('Altima\Lookbookslider\Helper\Data'); ?>
<?php $sliderId = '1'; ?>
<?php $blockObj = $block->getLayout()->createBlock('Altima\Lookbookslider\Block\SliderItem'); ?>
<?php $shotCollection =  $blockObj->getShotCollection($sliderId); ?>
<?php foreach($shotCollection as $shot): ?>
	<?php $productSku = $blockObj->getProducts($shot); ?>
    <?php if(in_array($_product->getSku(),$productSku)): ?>
    	<?php $slideId = $shot->getSlideId(); ?>
    	<?php $imagePath = $helper->getResizedUrl($shot->getImagePath(),'400','400'); ?>
        <div class="row">
            <div class="col-md-6 col-md-offset-6">
                <div class="product-shop-the-shot">
                    <h4>This product is featured in this shot:</h4>
                    <a href="<?php echo $this->getUrl('lookbookslider/index/view').'?slider_id='.$sliderId.'&slide_id='.$slideId; ?>">
                        <img src="<?php echo $imagePath; ?>" />
                        <span class="shop-the-shot-hover">Shop this shot</span>
                    </a>
                </div>
            </div>
        </div>
    	<?php break; ?>
 	<?php endif; ?>
 <?php endforeach; ?>