<a href="https://houseandhome.com/" target="_blank">Go To HouseandHome.com</a>
<ul class="social">
	<li><a href="https://houseandhome.com/facebook" target="_blank">
		<span class="ico-facebook"></span>
	</a></li>
	<li><a href="https://houseandhome.com/instagram" target="_blank">
		<span class="ico-instagram"></span>
	</a></li>
	<li><a href="https://houseandhome.com/pinterest" target="_blank">
		<span class="ico-pinterest"></span>
	</a></li>
	<li><a href="https://houseandhome.com/twitter" target="_blank">
		<span class="ico-twitter"></span>
	</a></li>
</ul>