<div class="panel-group" id="accordion">
<?php $i=1; ?>
<?php $faqs = $block->getFaqs(); ?>
<?php if(count($faqs) > 0): ?>
<?php foreach ($faqs as $faq): ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $i ?>">
                    <?php echo $i.'. '.$faq->getTitle() ?>
                </a>
            </h4>
        </div>
        <div id="collapse<?php echo $i ?>" class="panel-collapse collapse">
            <ul class="faqs-faq-list">
                <li class="faq-list-item">
                    <div class="faq-item-content">
                        <?php echo $faq->getContent(); ?>
                    </div>
                </li>
            </ul>
        </div>
    </div>    
<?php $i++; ?>
<?php endforeach; ?>
<?php endif; ?>
</div>
<p>
Don't see the answer to your questions above? <a href="<?php echo $this->getUrl('contact') ?>">Contact Us</a> at Shop H&H with any questions you may have.
</p>