<?php $tags = $this->getTags(); ?>
<div>
    <img src="<?php echo $this->getUrl('pub/media').'Tags/'.$tags->getImage() ?>" alt="<?php echo $this->escapeHtml($tags->getTitle()); ?>" />
    <div class="title"><?php echo $tags->getTitle(); ?></div>
    <div class="subtitle"><?php echo $tags->getSubtitle() ?></div>
</div>

<div class="tag_item_view">
    <?php $products = $this->getProductCollection(); ?>
    <div class="row tags-products">
        <?php
            foreach($products as $_product):
            $pro = $this->getProductData($_product);
            $image = $pro->getData('small_image');
        ?>
        <li class="col-md-3 tag-product">
            <a href="<?php echo $pro->getProductUrl() ?>">
                <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" />
            </a>
            <a href="<?php echo $pro->getProductUrl() ?>">
                <h4><?php echo $pro->getName(); ?></h4>
            </a>
            <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
            <?php if($customHelper->isProductNew($pro)): ?>
                <div class="new-product"><?php echo __('New'); ?></div>
            <?php endif; ?>
            <div class="editor-mini-quote"><?php echo $pro->getData('editors_quote'); ?></div>
            <h5><?php echo $this->getProductPrice($pro->getFinalPrice()); ?></h5>
        </li>
        <?php endforeach; ?>
    </div>
</div>