<?php $tags = $this->getTags(); ?>

<div class="category-view">
    <div class="category-image vcenter" style="background:url(<?php echo $this->getUrl('pub/media').'Tags/'.$tags->getImage() ?>)">
        <h2><?php echo $tags->getTitle(); ?><span><?php echo $tags->getSubtitle() ?></span></h2>
    </div>
</div>

<div class="container marginbottom-50">

    <div class="row tags-toolbar">
        <div class="col-md-6">
            <a href="<?php echo $tags->getLinkUrl() ?>" class="hover-effect">&lt; <?php echo $tags->getLinkText() ?></a>
        </div>
        <div class="col-md-6 text-right">
            <div class="toolbar toolbar-products clearfix">
                <div class="toolbar-sorter sorter col-md-4 hidden-xs">
                    <div class="styled-select">
                        <label class="sort-label" for="sorter">Sort</label>
                        <?php $sort = !empty($_GET['sort']) ? $_GET['sort'] : 'position'; ?>
                        <select id="sorter" data-role="sorter" class="sorter-options">
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=position'; ?>" <?php echo $sort == 'position' ? 'selected' : ''; ?>>Position</option>
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=price'; ?>" <?php echo $sort == 'price' ? 'selected' : ''; ?>>Price</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 margintop-50">
            <div class="tag_item_view">
                <?php $products = $this->getProductCollection($sort); ?>
                <div class="row tags-products">
                    <?php
                        foreach($products as $_product):
                        $pro = $this->getProductData($_product->getEntityId());
                        $image = $pro->getData('small_image');
                    ?>
                    <div class="col-md-3 tag-product">
                        <div class="product-img">
                            <a href="<?php echo $pro->getProductUrl() ?>">
                                <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" />
                            </a>
                            <a href="javascript: void(0);" data-quickview-url="weltpixel_quickview/catalog_product/view/id/<?php echo $pro->getId() ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
                        </div>
                        <h4>
                            <a href="<?php echo $pro->getProductUrl() ?>" class="hover-effect"><?php echo $pro->getName(); ?></a>
                        </h4>
                        <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
                        <?php if($customHelper->isProductNew($pro)): ?>
                            <div class="new-product"><?php echo __('New'); ?></div>
                        <?php endif; ?>
                        <p><?php echo $customHelper->limit_description($pro->getShortDescription(), 10); ?></p>
                        <h5><?php echo $this->getProductPrice($pro->getFinalPrice()); ?></h5>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

