<?php $tags = $this->getTags(); ?>

<div class="category-view">
    <div class="category-image vcenter" style="background:url(<?php echo $this->getUrl('pub/media').$tags->getImage() ?>)">
        <h2><?php echo $tags->getTitle(); ?><span><?php echo $tags->getSubtitle() ?></span></h2>
    </div>
</div>

<div class="container marginbottom-50">

    <div class="row tags-toolbar">
        <div class="col-md-3 col-xs-4">
            <a href="<?php echo $tags->getLinkUrl() ?>" class="hover-effect">&lt; <?php echo $tags->getLinkText() ?></a>
        </div>
        <div class="col-md-9 col-xs-7 text-right">

            <div class="toolbar toolbar-products clearfix">
                
                <div class="field limiter hidden-xs">
                    <div class="styled-select limiter-container ">
                        <label class="sort-label" for="limiter">
                            <span><?php echo __('Show') ?></span>
                        </label>
                        <?php $count = $this->getCount(); ?>
                        <?php if($count > 20): ?>
                            <?php $limit = !empty($_GET['limit']) ? $_GET['limit'] : '20'; ?>
                            <select id="limit" data-role="limit" class="limit-options">
                                <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?limit=20'; ?>" <?php echo $limit == '20' ? 'selected' : ''; ?>>20</option>
                                <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?limit=40'; ?>" <?php echo $limit == '40' ? 'selected' : ''; ?>>40</option>
                                <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?limit=all'; ?>" <?php echo $limit == 'all' ? 'selected' : ''; ?>>All</option>
                            </select>
                        <?php else: ?>
                            <?php echo $count; ?>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="toolbar-sorter sorter col-md-4 hidden-xs">
                    <div class="styled-select">
                        <label class="sort-label" for="sorter">Sort:</label>
                        <?php $sort = !empty($_GET['sort']) ? $_GET['sort'] : 'position'; ?>
                        <select id="sorter" data-role="sorter" class="sorter-options">
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=created_at'; ?>" <?php echo $sort == 'created_at' ? 'selected' : ''; ?>>Newest</option>
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=position'; ?>" <?php echo $sort == 'position' ? 'selected' : ''; ?>>Featured</option>
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=bestseller'; ?>" <?php echo $sort == 'bestseller' ? 'selected' : ''; ?>>Best Selling</option>
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=price_low'; ?>" <?php echo $sort == 'price_low' ? 'selected' : ''; ?>>Price Low to High</option>
                            <option value="<?php echo $this->getUrl('tags').'index/view/id/'.$tags->getTagsId().'/?sort=price_high'; ?>" <?php echo $sort == 'price_high' ? 'selected' : ''; ?>>Price High to Low</option>
                        </select>
                    </div>                    
                </div>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 margintop-50">
            <div class="tag_item_view">
                <?php $products = $this->getProductCollection($sort); ?>
                <div class="row tags-products">
                    <?php
                        foreach($products as $_product):
                        $pro = $this->getProductData($_product->getEntityId());
                        $image = $pro->getData('small_image');
                    ?>




                    <!--
                    <div class="col-md-3 tag-product">
                    -->
                    <div class="item product product-item-listing col-xs-6 col-sm-3 col-md-3">
                        <div class="product-item-info" >
                            <div class="product-img">
                                <a href="<?php echo $pro->getProductUrl() ?>">
                                    <img src="<?php echo $this->resize($image,240,240); ?>" />
                                </a>
                                <?php $quickViewUrl = $this->getUrl('').'weltpixel_quickview/catalog_product/view/id/'.$pro->getId(); ?>
                                <a href="javascript: void(0);" data-quickview-url="<?php echo $quickViewUrl ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
                            </div>

                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link hover-effect" href="<?php echo $pro->getProductUrl() ?>"><?php echo $pro->getName(); ?></a>
                                </strong>

                                <div class="product description product-item-description">
                                    <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
                                    <?php if($customHelper->getStockQty($pro)): ?>
                                        <span class="callout one-left"><?php echo __('Only 1 left'); ?></span>
                                    <?php elseif($customHelper->isEditorsPick($pro)): ?>
                                        <span class="callout editors-pick"><?php echo __('Editor’s Pick'); ?></span>
                                    <?php elseif($customHelper->isExclusive($pro)): ?>
                                        <span class="callout exclusive"><?php echo __('H&H exclusive'); ?></span> 
                                    <?php elseif($customHelper->isOnSale($pro)): ?>
                                        <span class="callout one-sale"><?php echo __('On Sale'); ?></span>
                                    <?php elseif($customHelper->isOneOfKind($pro)): ?>
                                        <span class="callout one-kind"><?php echo __('One of a Kind'); ?></span>
                                    <?php elseif($customHelper->isProductNew($pro)): ?>
                                        <span class="callout new-product"><?php echo __('New'); ?></span>
                                    <?php elseif($customHelper->isLastCall($pro)): ?>
                                        <span class="callout last-call"><?php echo __('Last Call'); ?></span>
                                    <?php endif; ?>
                                    <p><?php echo $customHelper->limit_description($pro->getShortDescription(), 10); ?></p>
                                </div>

                                <?php $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct'); ?>
                                <h5><?php echo $abstractProductBlock->getProductPrice($pro) ?></h5>
                            </div>

                        </div>
                    </div>




                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

