<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<div class="block review-add row">
    <div class="review-details-div">
        <div class="col-md-3 pull-right read-all-reviews text-right">
            <a href="#" class="btn-reviews display-none">Read all reviews <span></span></a>
        </div>
        <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>

<div class="col-md-3">
  <a href="#" class="btn btn-main btn-toggle-form">Add A Review</a>
</div>


            <form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="col-md-8 col-md-offset-2 review-form display-none" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                <?php echo $block->getBlockHtml('formkey'); ?>
                <?php echo $block->getChildHtml('form_fields_before')?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
                    <div class="field review-field-nickname required hidden">
                        <label for="nickname_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Nicknames') ?></span></label>
                        <div class="control">
                            <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:false}" data-bind="value: nickname()" />
                        </div>
                    </div>
                    <div class="field review-field-summary required hidden">
                        <label for="summary_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Summary') ?></span></label>
                        <div class="control">
                            <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:false}" data-bind="value: nickname()" />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Add A Review') ?></span></label>
                        <div class="control">
                            <textarea name="detail" class="review-text" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                </fieldset>

                <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                <span id="input-message-box"></span>
                <fieldset class="field required review-field-ratings">
                    <legend class="label"><span><?php /* @escapeNotVerified */ echo __('Your Rating') ?><span></legend>
                    <div class="control">
                        <div class="nested" id="product-review-table">
                            <?php foreach ($block->getRatings() as $_rating): ?>
                                <div class="field choice review-field-rating">
                                    <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                    <div class="control review-control-vote">
                                    <?php $options = $_rating->getOptions();?>
                                    <?php $iterator = 1; foreach ($options as $_option): ?>
                                        <input
                                            type="radio"
                                            name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                            id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                            value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                            class="radio"
                                            data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                            aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                        <label
                                            class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                            for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                            title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                            id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                            <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                        </label>
                                    <?php $iterator++; ?>
                                    <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                    </div>
                </fieldset>
            <?php endif ?>

            <div class="actions-toolbar review-form-actions">
                <div class="primary actions-primary">
                    <button type="submit" class="btn-main review-btn"><span><?php /* @escapeNotVerified */ echo __('Add A Review') ?></span></button>
                </div>
            </div>
        </form>


        <script type="text/x-magento-init">
        {
            "[data-role=product-review-form]": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            },
            "#review-form": {
                "Magento_Review/js/error-placement": {}
            }
        }
        </script>
        <?php else: ?>
            <div class="col-md-12 text-center">
            <!-- <h4><?php /* @escapeNotVerified */ echo __('Write A Review') ?></h4>
                <p><?php echo __('You must log in or create an acoount to review this product.') ?></p> -->
                <!--<p class="no-review-text">There are currently no reviews for this product.Be the first to write your review! You must be logged in to submit.</p>-->
                <a href="<?php echo $block->getLoginLink() ?>" class="btn btn-main btn-no-review"><?php echo __('Add A Review') ?></a>
								<span class="first-review">Be the first to write a review. You must be logged in to an account to submit.</span>
                <!-- <a href="<?php echo $block->getRegisterUrl() ?>" class="btn btn-main"><?php echo __('Sign Up') ?></a> -->
            </div>
        <?php endif ?>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
