<?php
/**
 * Awe Menu is quick, easy to setup and WYSIWYG menu management system
 *
 * Awe Menu by Kahanit(https://www.kahanit.com) is licensed under a
 * Creative Creative Commons Attribution-NoDerivatives 4.0 International License.
 * Based on a work at https://www.kahanit.com.
 * Permissions beyond the scope of this license may be available at https://www.kahanit.com.
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nd/4.0/.
 *
 * @author    Amit Sidhpura <amit@kahanit.com>
 * @copyright 2016 Kahanit
 * @license   http://creativecommons.org/licenses/by-nd/4.0/
 * @version   1.0.1.0
 */
?>

<div id="am-revisions-panel" class="panel panel-default">
    <div class="panel-heading">
        <img src="<?= $block->getViewFileUrl('Kahanit_AweMenu/img/revisions-icon.png'); ?>"/> <span>Revisions</span>
    </div>
    <div class="panel-body">
        <!-- revisions list -->
        <div id="am-revisions">
            <table id="am-revisions-table" class="table table-hover fancytree-container fancytree-ext-table fancytree-ext-glyph">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>