<?php
$size = ($block->getSize()) ? $block->getSize() : NULL;
$img = ($block->getValues()) ? $block->getValues() : NULL;
?>
<div id="lookbookimage" class="uploader">

    <span class="fileinput-button form-buttons">
        <span><?php /* @escapeNotVerified */ echo __('Browse Files') ?></span>
        <input id="fileupload" type="file" name="files[]"
               data-url="<?php /* @escapeNotVerified */ echo $block->getUrl('lookbookslider/slide/upload') ?>"
               >
        <input id="image_path" name="slide[image_path]" type="hidden" value="<?php echo $img; ?>"/>
        <input id="image_width" name="slide[image_width]" type="hidden" value="<?php echo $size['width']; ?>"/>
        <input id="image_height" name="slide[image_height]" type="hidden" value="<?php echo $size['height']; ?>"/>

    </span>
    <div class="clear"></div>
    <script id="lookbookimage-template" type="text/x-magento-template">
        <div id="<%- data.id %>" class="file-row">
        <span class="file-info"><%- data.name %> (<%- data.size %>)</span>
        <div class="progressbar-container progress-animated">
        <div class="progressbar upload-progress progress-bar" style="width: 0%;"></div>
        </div>
        <div class="clear"></div>
        </div>
    </script>
</div>
<div id="maket_image">
    <noscript>
    <p><?php echo __("Please enable JavaScript to use file uploader.") ?></p>
    </noscript>
</div>

<div id="LookbookImageBlock">
    <?php
    if ($img) {
        //   $img_src = $img_path . $img;
        $img_src = $this->helper('Altima\Lookbookslider\Helper\Data')->getResizedUrl($img, $size['width'], $size['height']);
        ?>            
        <img id="LookbookImage" src="<?php echo $img_src ?>" alt="<?php basename($img) ?>" />
        <?php
    }
    ?>
</div>    

<script>
    require([
        'jquery',
        'mage/template',
        'Magento_Ui/js/modal/alert',
        "mage/translate",
        'jquery/file-uploader',
        'altima/annotate'
    ], function ($, mageTemplate, alert) {


        $('#fileupload').fileupload({
            dataType: 'json',
            dropZone: '[data-tab-panel=image-management]',
            sequentialUploads: true,
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            add: function (e, data) {
                var progressTmpl = mageTemplate('#lookbookimage-template'),
                        fileSize,
                        tmpl;

                $.each(data.files, function (index, file) {
                    fileSize = typeof file.size == "undefined" ?
                            $.mage.__('We could not detect a size.') :
                            byteConvert(file.size);

                    data.fileId = Math.random().toString(33).substr(2, 18);

                    tmpl = progressTmpl({
                        data: {
                            name: file.name,
                            size: fileSize,
                            id: data.fileId
                        }
                    });

                    $(tmpl).appendTo('#lookbookimage');
                });

                $(this).fileupload('process', data).done(function () {
                    data.submit();
                });
            },
            done: function (e, data) {
                if (data.result && !data.result.error) {
                    if ($('#LookbookImageBlock'))
                    {
                        $.each($('#LookbookImageBlock').children(), function (index) {
                            $(this).remove();
                        });
                    }
                    $('<img id="LookbookImage" src="' + data.result.files[0].Url<?php echo $size['width'].'X'.$size['height']; ?> + '" alt="" />').load(function() {
                        $('#LookbookImageBlock').append(this);
                        $('#lookbookimage').trigger('addItem', data.result);
                    });

                    if ($('#advice-required-entry-image'))
                    {
                        $('#advice-required-entry-image').remove();
                    }
                    $('#image_path').val(data.result.files[0].name);
                    $('#image_path').removeClass('validation-failed');
                    $('#lookbookimage').trigger('addItem', data.result);
                } else {
                    $('#' + data.fileId)
                            .delay(2000)
                            .hide('highlight');
                    alert({
                        content: $.mage.__('We don\'t recognize or support this file extension type.')
                    });
                }
                $('#' + data.fileId).remove();
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('.progressbar.upload-progress').css(
                        'width',
                        progress + '%'
                        );
            }
        });


    });
</script>
