<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

?>
<div class="block newsletter-footer">
  <h4 class="title text-right">
    <?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter') ?>
    </h4>
  <div class="content text-right">
    <form class="form subscribe form-inline"
    novalidate
    action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail">
      <div class="newsletter-footer-inner">
        <input  name="email" type="email" class="newsletter-input" class="form-control"
                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                data-validate="{required:true, 'validate-email':true}"/>
        <button class="action btn-primary btn-subscribe" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
          <?php /* @escapeNotVerified */ echo __('Subscribe') ?>
        </button>
      </div>
    </form>
  </div>
</div>
