<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getItemConfigureUrl($item) ?>">
        <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
    </a>
<?php endif ?>
<?php if ($product->isSaleable()): ?>
        <a type="button" data-role="tocart" data-post='<?php /* @escapeNotVerified */ echo $block->getItemAddToCartParams($item)?>' title="<?php /* @escapeNotVerified */ echo __('Move to Cart') ?>" data-item-id="<?php /* @escapeNotVerified */ echo $item->getId()?>" class="action tocart">
            <span><?php /* @escapeNotVerified */ echo __('Move to Cart') ?></span>
        </a>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>

