<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="col-md-9 col-sm-8 col-xs-8 wishlist-item-details"> <!-- these divs are closed in cart.phtml -->
  <div class="row">
    <strong class="col-md-5 col-sm-12 col-xs-12 product-item-name">
      <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" title="<?php echo $block->escapeHtml($product->getName()) ?>" class="product-item-link">
        <?php echo $block->escapeHtml($product->getName()) ?>
      </a>
    </strong>
