
<h1 class="page-title basefont marginbottom-20"><span class="uppercase"><strong class="dietdidot font40 normal-case">Shop</strong> The Issue</span></h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h4 class="magazine-notice text-center">Look for this <i class="magazine"></i> icon in the <span>House & Home Magazine</span> to identify products that you buy on Shop H&H.</h4>
    </div>
</div>

<?php $_magazineItem = $this->getMagazine(); ?>
<div class="magazine-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="vcenter">
                        <div class="col-md-4 magazine-shot">
                            <img src="<?php echo $this->getUrl('pub/media').$_magazineItem->getImage() ?>" alt="<?php echo $this->escapeHtml($_magazineItem->getTitle()); ?>" class="img-responsive" />
                        </div>
                        <div class="col-md-7 col-md-offset-1 magazine-desc">
                            <h5 class="title"><?php echo $_magazineItem->getTitle(); ?></h5>
                            <h3 class="volume-name"><?php echo $_magazineItem->getVolumeName() ?></h3>
                            <div class="magazine-content"><?php echo $_magazineItem->getContent() ?></div>
                            <h4>Shop Now!</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="magazine_item_view">
    <div class="container">
        <?php $products = $this->getProductCollection(); ?>

        <div class="row toolbar marginbottom-40">
            <div class="col-md-6">
                <h4><?php echo count($products)." Items from Issue"; ?></h4>
            </div>
            <div class="col-md-6 text-right">
                <div class="row tags-toolbar">
                        <div class="toolbar toolbar-products clearfix">
                            <div class="toolbar-sorter sorter col-md-4 hidden-xs">
                                <div class="styled-select">
                                    <label class="sort-label" for="sorter">Sort</label>
                                    <select id="sorter" data-role="sorter" class="sorter-options">
                                        <option value="position" selected="selected">Position</option>
                                        <option value="price">Price</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>

        <div class="row magazine-products">
            <?php
                foreach($products as $_product):
                $pro = $this->getProductData($_product);
                $image = $pro->getData('small_image');
            ?>
            <div class="col-md-3 text-center magazine-product product-details-block">
                <div class="product-img">
                    <a href="<?php echo $pro->getProductUrl() ?>">
                        <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" />
                    </a>
                    <?php $quickViewUrl = $this->getUrl('').'weltpixel_quickview/catalog_product/view/id/'.$pro->getId(); ?>
                    <a href="javascript: void(0);" data-quickview-url="<?php echo $quickViewUrl ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
                </div>
                <?php $page = $pro->getData('issue_page_number'); ?>
                <?php if($page != NULL): ?>
                    <div class="page-number"><span><?php echo __('Page ') ?></span><?php echo $page; ?></div>
                <?php endif; ?>
                <h4><a href="<?php echo $pro->getProductUrl() ?>" class="hover-effect"><?php echo $pro->getName(); ?></a></h4>
                <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
                <?php if($customHelper->getStockQty($pro)): ?>
                    <span class="callout one-left"><?php echo __('Only 1 left'); ?></span>
                <?php elseif($customHelper->isEditorsPick($pro)): ?>
                    <span class="callout editors-pick"><?php echo __('Editor’s Pick'); ?></span>
                <?php elseif($customHelper->isExclusive($pro)): ?>
                    <span class="callout exclusive"><?php echo __('H&H exclusive'); ?></span> 
                <?php elseif($customHelper->isOnSale($pro)): ?>
                    <span class="callout one-sale"><?php echo __('On Sale'); ?></span>
                <?php elseif($customHelper->isOneOfKind($pro)): ?>
                    <span class="callout one-kind"><?php echo __('One of a Kind'); ?></span>
                <?php elseif($customHelper->isProductNew($pro)): ?>
                    <span class="callout new-product"><?php echo __('New'); ?></span>
                <?php elseif($customHelper->isLastCall($pro)): ?>
                    <span class="callout last-call"><?php echo __('Last Call'); ?></span>
                <?php endif; ?>
                <p><?php echo $customHelper->limit_description($pro->getShortDescription(), 10); ?></p>
                <h5><?php echo $this->getProductPrice($pro->getFinalPrice()); ?></h5>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<div class="container">
    <h1 class="page-title marginbottom-40"><span><?php echo __("Past H&H Issues") ?></span></h1>
    <?php $obj = $block->getLayout()->createBlock('Hhmedia\Magazine\Block\Magazine'); ?>
    <?php $_magazine = $obj->getCollection()->setPageSize(4); ?>
    <div class="row past-issue-listing">
    <?php foreach($_magazine as $magazine): ?>
        <?php if($magazine->getMagazineId() != $this->getRequest()->getParam('id')): ?>
            <div class="past-issue text-center col-md-3 col-sm-3 col-xs-6">
                <a href="<?php echo $obj->getItemUrl($magazine) ?>">
                    <img src="<?php echo $this->getUrl('pub/media').$magazine->getImage() ?>" alt="<?php echo $this->escapeHtml($magazine->getTitle()); ?>" />
                    <h4>
                        <a href="<?php echo $obj->getItemUrl($magazine) ?>" class="hover-effect">
                        <?php echo $this->escapeHtml($magazine->getTitle()) ?>
                        </a>
                    </h4>
                </a>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>