<?php $buttonTitle = __('View Full Details');?>
<?php $_product = $block->getProduct(); ?>

<div class="modal-btns">
	<div class="add-to-cart">
			<button type="submit"
							title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
							class="action btn-main"
							id="product-addtocart-button">
							<span><?php echo __('Add To Cart') ?></span>
			</button>
			<?php echo $block->getChildHtml('', true) ?>
	</div>
</div>