<?php $_collection = $this->getCollection(); ?>
<?php if ($_collection->getSize()): ?>
<div class="collection_list_view">
    <?php foreach ($_collection as $collectionItem): ?>
        <div id="item_<?php echo $collectionItem->getId() ?>" class="collection_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($collectionItem) ?>">
                    <?php echo $this->escapeHtml($collectionItem->getTitle()) ?>
                </a>
            </h2>

            <div class="collection_item_subtitle">
                <?php echo $this->formatDate($collectionItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($collectionItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($collectionItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($collectionItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Collection.'); ?></span></div>
<?php endif ?>
