<?php $collection = $this->getCollection(); ?>
<div class="category-view">
	<div class="category-image vcenter" style="background:url(<?php echo $this->getUrl('pub/media').$collection->getImage() ?>" alt="<?php echo $this->escapeHtml($collection->getCollectionTitle()); ?>)">
	    <h2>
	    	<?php echo $collection->getCollectionTitle(); ?><span><?php echo $collection->getCollectionSubtitle() ?></span>
	    </h2>
	</div>
</div>
<div class="container">
	<div class="row section-breadcrumb">
    	<div class="col-md-6"></div>
     	<div class="col-md-6 text-right">
        	<a href="<?php echo $collection->getLinkUrl() ?>" class="section-back hover-effect">
          		<?php echo $collection->getLinkText() ?> &gt;
        	</a>
      	</div>
	</div>
	<div class="row">
		<div class="collection_item_view marginbottom-40">
			<?php for($i=1; $i<=8; $i++): ?>
				<?php if($collection['title_'.$i] != NULL): ?>
					<h2 class="page-title"><span><?php echo $collection['title_'.$i] ?></span></h2>
					<div class="row collection-container">
						<?php $skus = array(trim($collection['sku_one_'.$i]), trim($collection['sku_two_'.$i]), trim($collection['sku_three_'.$i]), trim($collection['sku_four_'.$i])); ?>
						<?php foreach($skus as $sku): ?>
							<?php $product = $this->getProductBySku($sku); ?>
							<?php if($product != NULL): ?>
								<?php $image = $product->getData('small_image'); ?>
								<div class="item product product-item-listing col-xs-6 col-sm-3 col-md-3">
									<div class="product-item-info">
										<div class="category-thumb relative">
											<a href="<?php echo $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
					                			<img src="<?php echo $this->resize($image,240,240); ?>" />
					            			</a>
					            			<?php $quickViewUrl = $this->getUrl('').'weltpixel_quickview/catalog_product/view/id/'.$product->getId(); ?>
                                        	<a href="javascript: void(0);" data-quickview-url="<?php echo $quickViewUrl ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
										</div>

										<div class="product details product-item-details">
											<strong class="product name product-item-name">
										    	<a class="product-item-link hover-effect" href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName(); ?></a>
										    </strong>

										    <div class="product description product-item-description">
										    	<?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
							            		<?php if($customHelper->getStockQty($product)): ?>
								                    <span class="callout one-left"><?php echo __('Only 1 left'); ?></span>
								                <?php elseif($customHelper->isEditorsPick($product)): ?>
			                            			<span class="callout editors-pick"><?php echo __('Editor’s Pick'); ?></span>
			                            		<?php elseif($customHelper->isExclusive($product)): ?>
			                            			<span class="callout exclusive"><?php echo __('H&H exclusive'); ?></span> 
								                <?php elseif($customHelper->isOnSale($product)): ?>
								                    <span class="callout one-sale"><?php echo __('On Sale'); ?></span>
								                <?php elseif($customHelper->isOneOfKind($product)): ?>
								                    <span class="callout one-kind"><?php echo __('One of a Kind'); ?></span>
								                <?php elseif($customHelper->isProductNew($product)): ?>
								                    <span class="callout new-product"><?php echo __('New'); ?></span>
								                <?php elseif($customHelper->isLastCall($product)): ?>
			                            			<span class="callout last-call"><?php echo __('Last Call'); ?></span>
								                <?php endif; ?>
								                <p><?php echo $customHelper->limit_description($product->getShortDescription(),10) ?></p>
								                <?php $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct'); ?>
	                           					<h5 class="decorating-formula-price"><?php echo $abstractProductBlock->getProductPrice($product) ?></h5>
										    </div>
										</div>
	                           		</div>
								</div>
				        	<?php endif; ?>
						<?php endforeach; ?>
					</div>
					<div class="marginbottom-60 text-center">
						<a href="<?php echo $collection['link_'.$i]; ?>" class="btn btn-main btn-center"><?php echo __('See Full Collection') ?></a>
					</div>
				<?php endif; ?>
			<?php endfor; ?>
		</div>
	</div>
</div>