
<?php $_item = $this->getProduct(); ?>
<div class="actions-primary">
    <?php if ($_item->isSaleable()): ?>
        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
            <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
            </button>
            <a href="javascript: void(0);" data-quickview-url="<?php echo $this->getUrl('')?>weltpixel_quickview/catalog_product/view/id/<?php echo $_item->getEntityId() ?>" class="weltpixel-quickview" title="Quick View">
                <i class="mdi mdi-magnify"></i>
            </a>
        <?php else: ?>
            <?php 
                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
            ?>
            <button class="action tocart primary"
                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
            </button>
            <a href="javascript: void(0);" data-quickview-url="<?php echo $this->getUrl('')?>weltpixel_quickview/catalog_product/view/id/<?php echo $_item->getEntityId() ?>" class="weltpixel-quickview" title="Quick View">
                <i class="mdi mdi-magnify"></i>
            </a>       
        <?php endif; ?>
    <?php else: ?>
        <?php if ($_item->getIsSalable()): ?>
            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
        <?php else: ?>
            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
        <?php endif; ?>
    <?php endif; ?>
</div>