<?php
$sliderId = $this->getRequest()->getParam('slider_id');
$slideId =$this->getRequest()->getParam('slide_id');
$blockObj = $block->getLayout()->createBlock('Altima\Lookbookslider\Block\SliderItem');
$helper = $this->helper('Altima\Lookbookslider\Helper\Data');

if ($helper->getEnabled()) :
    $slideCollection = $blockObj->getShotCollection($sliderId);
    if (!empty($slideCollection) && $slideCollection->getSize()) :
        $currentUrl = $blockObj->getUrl();
        $styleSlide = $blockObj->getSlider()->getStyleSlide();
        $slider = $blockObj->getSlider();
        $htmlId = $blockObj->getFlexsliderHtmlId();
        $navigation = ($slider->getNavigation() == 1) ? TRUE : FALSE;
        $navigationHover = ($slider->getNavigationHover() == 1) ? TRUE : FALSE;
        $thumbnails = ($slider->getThumbnails() == 1) ? TRUE : FALSE;
        $contentBefore = $slider->getContentBefore();
        $contentAfter = $slider->getContentAfter();

        $effect = $slider->getEffect();
        $effect_opt = FALSE;
        if ($effect == 'shuffle_revert') {
            $effect = 'shuffle';
            $effect_opt = 'data-cycle-reverse=true';
        }
        if ($effect == '' || $effect == 'all') {
            $effect = 'fade,' .
                    'scrollLeft,scrollRight,scrollVert,scrollUp,scrollDown,' .
                    'cover,tileSlide,tileSlideHorz,tileBlind,tileBlindHorz,' .
                    'slideLeft,slideRight,slideTop,slideBottom,slideLeftTop,' .
                    'slideLeftBottom,slideRightTop,slideRightBottom';
        }
        $effect_arr = FALSE;
        $effect_arr = strpos($effect, ',');
        if ($effect_arr) {
            $effect = explode(',', $effect);
        }

        $time = $slider->getTime();
        $trans_period = $slider->getTransPeriod();
        $thumb = TRUE;
        if (count($slideCollection) <= 1){
            $navigation = FALSE;
            $thumbnails = FALSE;
            $thumb = FALSE;
        }
        ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $blockObj->getViewFileUrl('Altima_Lookbookslider::css/lookbookslider.css') ?>">


<div class="home-slider lookbook-container">

  <div class="row no-gutters vcenter-flex display-block-xs">
    <div class="col-lg-8 col-md-7 homepage-hero">


        <div class="lookbookslider-top">
            <?php if ($contentBefore): ?>
              <div class="content-before"><?php echo $contentBefore; ?></div>
            <?php endif; ?>
            <div id="lookbookslider_container_<?php echo $slider->getId() ?>"  class="lookbookslider-container">
                <div class="cycle-slideshow1" id="lookbookslider_<?php echo $slider->getId() ?>"
                     

        <?php if (!$thumbnails && $thumb): ?>
                         data-cycle-pager="#pagernav_<?php echo $slider->getId() ?> .cycle"
                         data-cycle-pager-template="<li><span> {{slideNum}} </span></li>"
                     <?php endif; ?>
        <?php if ($navigation): ?>
                         data-cycle-prev="#lookbookslider_<?php echo $slider->getId() ?> .slide-prev"
                         data-cycle-next="#lookbookslider_<?php echo $slider->getId() ?> .slide-next"
        <?php endif; ?>
                     >





                    <?php $slide_ind = 1; ?>

                    <?php foreach ($slideCollection as $slide): ?>
                        <?php if($slide->getId() == $slideId): ?>
                        <div class="slide" style="background-image:url('<?php echo $blockObj->getSlideImageUrl($slide) ?>');"
                        <?php
                        if ($effect_arr):
                            $ind = array_rand($effect, 1);
                            echo 'data-cycle-fx="' . $effect[$ind] . '"';
                        endif;
                        ?>
                             >
                                

                                <img alt="Slide <?php echo $slide->getId(); ?>" class="shoptheshot-img" src="<?php echo $blockObj->getSlideImageUrl($slide) ?>"/>
                                <?php $hotspots[] = $blockObj->getHotspotsWithProductDetails($slide); ?>




                        </div>
                        <?php $hotspots[] = $blockObj->getHotspotsWithProductDetails($slide); ?>
                        <?php $slide_ind++; ?>
            <?php endif; ?>
        <?php endforeach ?>
                    <div id="progress"></div>
                </div>


                
                <?php if ($thumbnails && $thumb): ?>
                    <?php $count_pager = 5; ?>
                    <?php
                    if (count($slideCollection) < 5) {
                        $count_pager = $slideCollection->getSize();
                    }
                    ?>
                    <div id="pagernav_<?php echo $slider->getId() ?>" class="pagernav" style="max-width:<?php echo $slider->getWidth(); ?>px;" >
                        <ul  id="pagernav_<?php echo $slider->getId() ?>_thumb" class="cycle-slideshow1" 
                             data-cycle-fx="carousel" 
                             data-cycle-slides="> li.thumb"
                             data-cycle-timeout="0"
                             data-cycle-carousel-fluid="true"
                             data-cycle-log="false"
                             data-cycle-carousel-visible="<?php echo $count_pager; ?>"
                             data-allow-wrap="false"
                             >

                        </ul>
                    </div>
        <?php elseif ($thumb): ?>
                    <div id="pagernav_<?php echo $slider->getId() ?>" class="pagernav" >
                        <ul class="cycle">

                        </ul>
                    </div>
        <?php endif; ?>

            </div>
            <?php if ($contentAfter): ?>
                <div class="content-after"><?php echo $contentAfter; ?></div>
        <?php endif; ?>
        </div>


</div>



<?php foreach ($slideCollection as $slide): ?>
    <?php if($slide->getId() == $slideId): ?>
        <div class="col-lg-4 col-md-5 mood-bg vcenter display-block-xs" style="background-image:url(<?php echo $this->getUrl('pub/media').'Altima/Lookbookslider/Slide/image'.$slide->getBgImage() ?>);">

            <div class="hotspot-details vcenter">
                <div class="hotspot-default visible">
                    <h5>Shop the shot</h5>
                    <h1 style="color:<?php echo $slide->getColor() ?>"><?php echo $slide->getTitle(); ?></h1>
                    <p><?php echo $slide->getCaption(); ?></p>




                    <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
                      <a class="icon-share addthis_button_more">
                        <span><img src="<?php echo $this->getViewFileUrl('images/share-icon.png'); ?>" /></span>
                        <span>Share this Shot</span>
                      </a>
                    </div>
                    <div class="clearfix"></div>


                    <!--
                    <ul class="social">
                      <li><a href="https://houseandhome.com/facebook" target="_blank">
                        <span class="ico-facebook"></span>
                      </a></li>
                      <li><a href="https://houseandhome.com/twitter" target="_blank">
                        <span class="ico-twitter"></span>
                      </a></li>
                      <li><a href="https://houseandhome.com/pinterest" target="_blank">
                        <span class="ico-pinterest"></span>
                      </a></li>
                      <li><a href="mailto:support@houseandhome.com">
                        <span class="ico-mail"></span>
                      </a></li>
                    </ul
                    -->


                    <?php $noteId = $slide->getLink(); ?>
                    <?php if($noteId != NULL && $noteId > 0): ?>
                      <a href="<?php echo $this->getUrl('notes').'index/view/id/'.$noteId; ?>" class="btn-fullscreen">Read All Decorating Notes</a>
                    <?php endif; ?>
                </div>
                <div class="hotspot-details-placeholder hidden"></div>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach ?>


</div>
</div>

    
      <?php $currentSlide = $blockObj->getSlide($sliderId, $slideId); ?>
      
            <?php foreach($currentSlide as $cs): ?>
              
      <?php if($cs['story_template'] == 1): ?>
        <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <h2 class="page-title marginbottom-40">
                    <span><?php echo $cs->getCollectionTitle() ?></span>
                  </h2>
                </div>
              </div>
                <div class="row">
                  <div class="col-md-6 col-sm-6 col-xs-6 product-stories-desc">
                      <img src="<?php echo $this->getUrl('pub/media').'Altima/Lookbookslider/Slide/image'.$cs->getImageOne() ?>" />
                      <h3><?php echo $cs->getTitleOne() ?></h3>
                      <p><?php echo $cs->getDescriptionOne() ?></p>
                      <a href="<?php echo $cs->getLinkOne() ?>" class="hover-effect"><?php echo __('shop collection >') ?></a>
                  </div>
                  <div class="col-md-6 col-sm-6 col-xs-6 product-stories-desc">
                      <img src="<?php echo $this->getUrl('pub/media').'Altima/Lookbookslider/Slide/image'.$cs->getImageTwo() ?>" />
                      <h3><?php echo $cs->getTitleTwo() ?></h3>
                      <p><?php echo $cs->getDescriptionTwo() ?></p>
                      <a href="<?php echo $cs->getLinkTwo() ?>" class="hover-effect"><?php echo __('shop collection >') ?></a>
                  </div>
                </div>
                <div class="clearfix"></div>
                <?php $skus = array(trim($cs->getSkuOne()), trim($cs->getSkuTwo()), trim($cs->getSkuThree()), trim($cs->getSkuFour())); ?>

                <div class="row">
                  <div class="col-md-12">
                    <h2 class="highlighted-products-title"><span>Highlighted Products</h2>
                  </div>
                </div>
                <div class="row product-stories-products">
                  <?php foreach($skus as $sku): ?>
                    <?php $product = $blockObj->getProductBySku($sku); ?>
                    <?php if($product != NULL): ?>
                      <?php $image = $product->getData('small_image'); ?>
                      <div class="item product product-item-listing col-xs-6 col-sm-3 col-md-3">
                        <div class="product-item-info">
                          <div class="category-thumb relative">
                              <a href="<?php echo $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <img src="<?php echo $this->getUrl('pub/media/catalog').'product'.$image ?>" />
                              </a>
                              <?php $quickViewUrl = $this->getUrl('').'weltpixel_quickview/catalog_product/view/id/'.$product->getId(); ?>
                              <a href="javascript: void(0);" data-quickview-url="<?php echo $quickViewUrl ?>" class="weltpixel-quickview quickview-bar2" title="Quick View">Quick Look</a>
                          </div>
                          <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                              <a class="product-item-link hover-effect" href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName(); ?></a>
                            </strong>
                            <div class="product description product-item-description">
                              <?php $customHelper = $this->helper('Hhmedia\Productpage\Helper\Newproduct'); ?>
                              <?php if($customHelper->getStockQty($product)): ?>
                                  <span class="callout one-left"><?php echo __('Only 1 left'); ?></span>
                              <?php elseif($customHelper->isEditorsPick($product)): ?>
                                  <span class="callout editors-pick"><?php echo __('Editor’s Pick'); ?></span>
                              <?php elseif($customHelper->isExclusive($product)): ?>
                                  <span class="callout exclusive"><?php echo __('H&H exclusive'); ?></span> 
                              <?php elseif($customHelper->isOnSale($product)): ?>
                                  <span class="callout one-sale"><?php echo __('On Sale'); ?></span>
                              <?php elseif($customHelper->isOneOfKind($product)): ?>
                                  <span class="callout one-kind"><?php echo __('One of a Kind'); ?></span>
                              <?php elseif($customHelper->isProductNew($product)): ?>
                                  <span class="callout new-product"><?php echo __('New'); ?></span>
                              <?php elseif($customHelper->isLastCall($product)): ?>
                                  <span class="callout last-call"><?php echo __('Last Call'); ?></span>
                              <?php endif; ?>
                              <p><?php echo $customHelper->limit_description($product->getShortDescription(),10) ?></p>
                              <?php $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct'); ?>
                              <h5><?php echo $abstractProductBlock->getProductPrice($product) ?></h5>
                            </div>
                          </div>
                        </div>
                      </div>
                    <?php endif; ?>
                <?php endforeach; ?>
              </div>
              <div class="row">
                <?php if($cs->getTitleThree() != ''): ?>
                  <div class="col-md-6 col-sm-6 col-xs-6 product-stories-desc">
                    <img src="<?php echo $this->getUrl('pub/media').'Altima/Lookbookslider/Slide/image'.$cs->getImageThree() ?>" />
                    <h3><?php echo $cs->getTitleThree() ?></h3>
                    <p><?php echo $cs->getDescriptionThree() ?></p>
                    <a href="<?php echo $cs->getLinkThree() ?>" class="hover-effect"><?php echo __('shop collection >') ?></a>
                  </div>
                <?php endif;?>
                <?php if($cs->getTitleFour() != ''): ?>
                  <div class="col-md-6 col-sm-6 col-xs-6 product-stories-desc">
                    <img src="<?php echo $this->getUrl('pub/media').'Altima/Lookbookslider/Slide/image'.$cs->getImageFour() ?>" />
                    <h3><?php echo $cs->getTitleFour() ?></h3>
                    <p><?php echo $cs->getDescriptionFour() ?></p>
                    <a href="<?php echo $cs->getLinkFour() ?>" class="hover-effect"><?php echo __('shop collection >') ?></a>
                  </div>
                <?php endif; ?>
              </div>
              <div class="row marginbottom-60">
                <div class="col-md-12 text-center">
                  <a href="<?php echo $cs->getCollectionLink() ?>" class="btn btn-main btn-center">
                    <?php echo __('See All Products In Collection') ?>
                  </a>
                   </div>
        </div>
      </div>
      <?php //endif; ?>

    <?php else: ?>

      <div class="container">
                <div class="row">
                    <div class="page-title marginbottom-40"><span><?php echo __("In This Shot") ?></span></div>
                    <div class="products list items product-items row">
                    <?php foreach ($slideCollection as $slide): ?>
                        <?php if($slide->getId() == $slideId): ?>
                            <?php $products = $blockObj->getProductCollection($slide); ?>
                            <?php foreach($products as $_product): ?>
                                <div class="item product product-item-listing col-xs-6 col-sm-3 col-md-3">
                                    <?php echo $_product['text']; ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </div>
                </div>
            </div>

            <div class="more-shots row no-gutters">
                <h2 class="page-title basefont"><span><strong class="dietdidot">Shop</strong> MORE SHOTS</span></h2>
                <h4 class="subtitle"><?php echo __('Inspiration for every room in the house') ?></h4>
                <?php $shotCollection =  $blockObj->getShotCollection($sliderId); ?>
                <?php foreach($shotCollection as $shot): ?>
                    <?php if($slideId != $shot->getSlideId()): ?> 
                        <?php $imagePath = $helper->getResizedUrl($shot->getImagePath(),'400','400'); ?>
                        <div class="col-md-3">
                            <div class="shot-thumb">
                                <a href="<?php echo $this->getUrl('lookbookslider/index/view').'?slider_id='.$sliderId.'&slide_id='.$shot->getSlideId(); ?>">
                                    <img src="<?php echo $imagePath; ?>" />
                                    <div class="shot-thumb-meta">
                                        <h4><span>Shop</span></h4>
                                        <span class="title" style="color:<?php echo $shot->getColor() ?>"><?php echo $shot->getTitle(); ?></span>
                                    </div>
                                </a>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>

    <?php endif; ?>
          <?php break; endforeach; ?>


              
   


        <script type="text/javascript">

        (function () {
            var flexSliderSelector = '<?php echo $htmlId; ?>';
            require(['jquery', 'altima/cycle', 'altima/hotspots', 'altima/cyclecarousel', 'altima/cyclecenter', 'altima/cycleAddEffects', 'altima/cycleflip'], function (jQuery) {

            /* this was the problem line for why it wouldn't load in firefox..
            var $altima_jq = jQuery.noConflict();
            */
            // even this wont work in firefox: jQuery(window).load(function() {
            
            jQuery(document).ready(function() {
              jQuery('#lookbookslider_<?php echo $slider->getId() ?>').cycle();
              jQuery('#pagernav_<?php echo $slider->getId() ?>_thumb').cycle();
              var hotspots = <?php echo json_encode($hotspots); ?>;
              
              jQuery('#lookbookslider_<?php echo $slider->getId() ?> > div.slide:not(.cycle-sentinel)').each(function (i) {
                var ind = jQuery(this).index();
                var slide = jQuery(this);
                jQuery.setHotspots(slide, hotspots[i]);
              });
            });
          });
        })();
        </script>
        <?php
    endif;
endif;
?>
