<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>
<?php if ($block->isWishListAllowed()) : ?>
<a 	href="#"
		data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
		data-action="add-to-wishlist">
		<span class="single-product-wishlist"><i class="ion-ios-heart-outline"></i></span>
</a>
<?php endif; ?>
<script type="text/x-magento-init">
	{
	  "body": {
	    "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
	  }
	}
</script>
