<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>

<?php if ($block->isWishListAllowed()) : ?>
	<?php if($this->getRequest()->getModuleName() == "weltpixel_quickview"): ?>
		<?php $id = $block->getProductId(); ?>
		<a target="_parent"
			href="<?php echo $this->getUrl('wishlist').'index/add/product/'.$id.'/form_key/71UD2LR6HIYz7Uwj'; ?>"
			data-action="add-to-wishlist">
			<span class="single-product-wishlist">
				<img src="<?php echo $this->getViewFileUrl('images/wishlist-save.png'); ?>" />
				<span>Add to Wishlist</span>
			</span>
		</a>
	<?php else: ?>
		<a 	href="#"
			data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
			data-action="add-to-wishlist">
			<span class="single-product-wishlist">
				<img src="<?php echo $this->getViewFileUrl('images/wishlist-save.png'); ?>" />
				<span>Add to Wishlist</span>
			</span>
		</a>
	<?php endif; ?>
<?php endif; ?>
<script type="text/x-magento-init">
	{
	  "body": {
	    "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
	  }
	}
</script>