<?php
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
	$categories = $categoryCollection->create();
	$categories->addAttributeToSelect('*');
	$categories->addAttributeToFilter('page_not_found', 1);
?>
<div class="listing-404">
	<?php foreach ($categories as $category): ?>
		<div class="col-md-4 product-404">
	    <a href="<?php echo $category->getUrl() ?>">
	    	<img src="<?php echo $category->getAdditionalImage() ?>" width="400" height="400" />
	    	<?php echo $category->getName() ?>
	    </a>
	  </div>
	<?php endforeach; ?>
</div>

