<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<!-- <div class="field limiter hidden-xs">
    <div class="styled-select">
        <select id="limiter" data-role="limiter" class="limiter-options">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?php /* @escapeNotVerified */ echo 'SHOW : '.$_limit ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
 -->

 <div class="field limiter hidden-xs">
    <div class="styled-select limiter-container ">
        <label class="sort-label" for="limiter">
            <span><?php /* @escapeNotVerified */ echo __('Show') ?></span>
        </label>

        <select id="limiter" data-role="limiter" class="sorter-options limiter-option">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?php /* @escapeNotVerified */ echo $_limit ?>
                </option>
            <?php endforeach; ?>
        </select>
   </div>
</div>
