<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>

<div class="field limiter form-inline pull-right hidden-xs">
    <div class="dropdown">
      <button class="btn dropdown-toggle btn-view-list" type="button" data-toggle="dropdown">View
      <span class="caret"></span></button>
        <ul id="limiter" data-role="limiter" class="dropdown-menu limiter-options ">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <li value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?php /* @escapeNotVerified */ echo 'View '. $_limit ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<div class="category-dropdown hidden-lg hidden-md hidden-sm visible-xs">
    <div class="dropdown">
      <button class="btn dropdown-toggle btn-view-list2" type="button" data-toggle="dropdown">View
      <span class="caret"></span></button>
        <ul id="limiter" data-role="limiter" class="dropdown-menu limiter-options2">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <li value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?php /* @escapeNotVerified */ echo 'View '. $_limit ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>