<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter hidden-xs">
    <?php
        $active = '';
        $currentUrl = strtok($block->getPagerUrl(), '?');
        $dir = $this->getRequest()->getParam('product_list_dir');
        $order = $this->getRequest()->getParam('product_list_order');
        $limit = $this->getRequest()->getParam('product_list_limit');
        if($limit != ''){
            $latest = $currentUrl.'?product_list_dir=desc'.'&product_list_order=position'.'&product_list_limit='.$limit;
            $priceLH = $currentUrl.'?product_list_dir=asc'.'&product_list_order=price'.'&product_list_limit='.$limit;
            $priceHL = $currentUrl.'?product_list_dir=desc'.'&product_list_order=price'.'&product_list_limit='.$limit;
        }else{
            $latest = $currentUrl.'?product_list_dir=desc'.'&product_list_order=position';
            $priceLH = $currentUrl.'?product_list_dir=asc'.'&product_list_order=price';
            $priceHL = $currentUrl.'?product_list_dir=desc'.'&product_list_order=price';
        }  
    ?>
    <label class="sorter-label" for="sorter"><?php echo __('Sort By:') ?></label>
    <a title="<?php echo __('Latest') ?>" href="<?php echo $latest ?>">
        <?php if($order == 'position') { $active = 'active'; }else{$active = 'active';} ?> 
        <span class="<?php echo $active ?>"><?php echo __('Latest') ?></span>
    </a>
    <a title="<?php echo __('Price (Low to High)') ?>" href="<?php echo $priceLH ?>">
        <?php if($order == 'price' && $dir=='asc') { $active = 'active';}else{$active='';} ?> 
        <span class="<?php echo $active ?>"><?php echo __('Price (Low to High)') ?></span>
    </a>
    <a title="<?php echo __('Price (High to Low)') ?>" href="<?php echo $priceHL ?>">
        <?php if($order == 'price' && $dir=='desc'){$active = 'active';}else{$active='';} ?>
        <span class="<?php echo $active ?>"><?php echo __('Price (High to Low)') ?></span>
    </a>
</div>
<div class="sorter-mobile pull-left hidden-lg hidden-md hidden-sm visible-xs">
    <select onchange="setLocation(this.value)">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($_order != 'Price'): ?>
                <option value="<?php echo $latest ?>"<?php if($block->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo __('Latest') ?>
                </option>
            <?php else: ?>
                <option value="<?php echo $priceLH ?>"<?php if($block->isOrderCurrent($_key) && $block->getCurrentDirection() == 'asc'): ?> selected="selected"<?php endif; ?>>
                    <?php echo __('Price (Low to High)') ?>
                </option> 
                <option value="<?php echo $priceHL ?>"<?php if($block->isOrderCurrent($_key) && $block->getCurrentDirection() == 'desc'): ?> selected="selected"<?php endif; ?>>
                    <?php echo __('Price (High to Low)') ?>
                </option> 
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
</div>